// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.io.proto

package marmot.proto.io;

public final class MarmotIo {
  private MarmotIo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_io_GroupKeyValueProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_io_GroupKeyValueProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017marmot.io.proto\022\017marmot.proto.io\032\014marm" +
      "ot.proto\"\371\001\n\022GroupKeyValueProto\022\030\n\020key_v" +
      "alues_count\030\001 \001(\005\022\030\n\020tag_values_count\030\002 " +
      "\001(\005\022\032\n\022order_values_count\030\003 \001(\005\022\'\n\005value" +
      "\030\004 \003(\0132\030.marmot.proto.ValueProto\0223\n\nsort" +
      "_order\030\005 \003(\0162\037.marmot.proto.io.SortOrder" +
      "Proto\0225\n\013nulls_order\030\006 \003(\0162 .marmot.prot" +
      "o.io.NullsOrderProto*#\n\016SortOrderProto\022\007" +
      "\n\003ASC\020\000\022\010\n\004DESC\020\001*&\n\017NullsOrderProto\022\t\n\005" +
      "FIRST\020\000\022\010\n\004LAST\020\001B\023\n\017marmot.proto.ioP\001P\000" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          marmot.proto.Marmot.getDescriptor(),
        }, assigner);
    internal_static_marmot_proto_io_GroupKeyValueProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_marmot_proto_io_GroupKeyValueProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_io_GroupKeyValueProto_descriptor,
        new java.lang.String[] { "KeyValuesCount", "TagValuesCount", "OrderValuesCount", "Value", "SortOrder", "NullsOrder", });
    marmot.proto.Marmot.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
