// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.internal.proto

package marmot.proto;

public interface CreateSpatialIndexInfoProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.optor.proto.CreateSpatialIndexInfoProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataset = 1;</code>
   */
  java.lang.String getDataset();
  /**
   * <code>string dataset = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatasetBytes();

  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column = 2;</code>
   */
  boolean hasGeometryColumn();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column = 2;</code>
   */
  marmot.proto.GeometryColumnInfoProto getGeometryColumn();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column = 2;</code>
   */
  marmot.proto.GeometryColumnInfoProtoOrBuilder getGeometryColumnOrBuilder();

  /**
   * <code>string hdfs_path = 3;</code>
   */
  java.lang.String getHdfsPath();
  /**
   * <code>string hdfs_path = 3;</code>
   */
  com.google.protobuf.ByteString
      getHdfsPathBytes();
}
