// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.internal.proto

package marmot.proto;

public interface MarmotCoreProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.optor.proto.MarmotCoreProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string xml_string = 1;</code>
   */
  java.lang.String getXmlString();
  /**
   * <code>string xml_string = 1;</code>
   */
  com.google.protobuf.ByteString
      getXmlStringBytes();
}
