// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.internal.proto

package marmot.proto;

/**
 * Protobuf type {@code marmot.optor.proto.ScriptRecordTransformProto}
 */
public  final class ScriptRecordTransformProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.optor.proto.ScriptRecordTransformProto)
    ScriptRecordTransformProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScriptRecordTransformProto.newBuilder() to construct.
  private ScriptRecordTransformProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScriptRecordTransformProto() {
    transformExpr_ = "";
    importedClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScriptRecordTransformProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            marmot.proto.RecordSchemaProto.Builder subBuilder = null;
            if (optionalOutputRecordSchemaCase_ == 1) {
              subBuilder = ((marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_).toBuilder();
            }
            optionalOutputRecordSchema_ =
                input.readMessage(marmot.proto.RecordSchemaProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_);
              optionalOutputRecordSchema_ = subBuilder.buildPartial();
            }
            optionalOutputRecordSchemaCase_ = 1;
            break;
          }
          case 18: {
            marmot.proto.RecordSchemaProto.Builder subBuilder = null;
            if (optionalAddedRecordSchemaCase_ == 2) {
              subBuilder = ((marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_).toBuilder();
            }
            optionalAddedRecordSchema_ =
                input.readMessage(marmot.proto.RecordSchemaProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_);
              optionalAddedRecordSchema_ = subBuilder.buildPartial();
            }
            optionalAddedRecordSchemaCase_ = 2;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            optionalInitializerCase_ = 3;
            optionalInitializer_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            transformExpr_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              importedClasses_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            importedClasses_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        importedClasses_ = importedClasses_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.MarmotInternal.internal_static_marmot_optor_proto_ScriptRecordTransformProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.MarmotInternal.internal_static_marmot_optor_proto_ScriptRecordTransformProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.ScriptRecordTransformProto.class, marmot.proto.ScriptRecordTransformProto.Builder.class);
  }

  private int bitField0_;
  private int optionalOutputRecordSchemaCase_ = 0;
  private java.lang.Object optionalOutputRecordSchema_;
  public enum OptionalOutputRecordSchemaCase
      implements com.google.protobuf.Internal.EnumLite {
    OUTPUT_RECORD_SCHEMA(1),
    OPTIONALOUTPUTRECORDSCHEMA_NOT_SET(0);
    private final int value;
    private OptionalOutputRecordSchemaCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptionalOutputRecordSchemaCase valueOf(int value) {
      return forNumber(value);
    }

    public static OptionalOutputRecordSchemaCase forNumber(int value) {
      switch (value) {
        case 1: return OUTPUT_RECORD_SCHEMA;
        case 0: return OPTIONALOUTPUTRECORDSCHEMA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OptionalOutputRecordSchemaCase
  getOptionalOutputRecordSchemaCase() {
    return OptionalOutputRecordSchemaCase.forNumber(
        optionalOutputRecordSchemaCase_);
  }

  private int optionalAddedRecordSchemaCase_ = 0;
  private java.lang.Object optionalAddedRecordSchema_;
  public enum OptionalAddedRecordSchemaCase
      implements com.google.protobuf.Internal.EnumLite {
    ADDED_RECORD_SCHEMA(2),
    OPTIONALADDEDRECORDSCHEMA_NOT_SET(0);
    private final int value;
    private OptionalAddedRecordSchemaCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptionalAddedRecordSchemaCase valueOf(int value) {
      return forNumber(value);
    }

    public static OptionalAddedRecordSchemaCase forNumber(int value) {
      switch (value) {
        case 2: return ADDED_RECORD_SCHEMA;
        case 0: return OPTIONALADDEDRECORDSCHEMA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OptionalAddedRecordSchemaCase
  getOptionalAddedRecordSchemaCase() {
    return OptionalAddedRecordSchemaCase.forNumber(
        optionalAddedRecordSchemaCase_);
  }

  private int optionalInitializerCase_ = 0;
  private java.lang.Object optionalInitializer_;
  public enum OptionalInitializerCase
      implements com.google.protobuf.Internal.EnumLite {
    INITIALIZER_EXPR(3),
    OPTIONALINITIALIZER_NOT_SET(0);
    private final int value;
    private OptionalInitializerCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptionalInitializerCase valueOf(int value) {
      return forNumber(value);
    }

    public static OptionalInitializerCase forNumber(int value) {
      switch (value) {
        case 3: return INITIALIZER_EXPR;
        case 0: return OPTIONALINITIALIZER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OptionalInitializerCase
  getOptionalInitializerCase() {
    return OptionalInitializerCase.forNumber(
        optionalInitializerCase_);
  }

  public static final int OUTPUT_RECORD_SCHEMA_FIELD_NUMBER = 1;
  /**
   * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
   */
  public boolean hasOutputRecordSchema() {
    return optionalOutputRecordSchemaCase_ == 1;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
   */
  public marmot.proto.RecordSchemaProto getOutputRecordSchema() {
    if (optionalOutputRecordSchemaCase_ == 1) {
       return (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_;
    }
    return marmot.proto.RecordSchemaProto.getDefaultInstance();
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
   */
  public marmot.proto.RecordSchemaProtoOrBuilder getOutputRecordSchemaOrBuilder() {
    if (optionalOutputRecordSchemaCase_ == 1) {
       return (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_;
    }
    return marmot.proto.RecordSchemaProto.getDefaultInstance();
  }

  public static final int ADDED_RECORD_SCHEMA_FIELD_NUMBER = 2;
  /**
   * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
   */
  public boolean hasAddedRecordSchema() {
    return optionalAddedRecordSchemaCase_ == 2;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
   */
  public marmot.proto.RecordSchemaProto getAddedRecordSchema() {
    if (optionalAddedRecordSchemaCase_ == 2) {
       return (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_;
    }
    return marmot.proto.RecordSchemaProto.getDefaultInstance();
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
   */
  public marmot.proto.RecordSchemaProtoOrBuilder getAddedRecordSchemaOrBuilder() {
    if (optionalAddedRecordSchemaCase_ == 2) {
       return (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_;
    }
    return marmot.proto.RecordSchemaProto.getDefaultInstance();
  }

  public static final int INITIALIZER_EXPR_FIELD_NUMBER = 3;
  /**
   * <code>string initializer_expr = 3;</code>
   */
  public java.lang.String getInitializerExpr() {
    java.lang.Object ref = "";
    if (optionalInitializerCase_ == 3) {
      ref = optionalInitializer_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (optionalInitializerCase_ == 3) {
        optionalInitializer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string initializer_expr = 3;</code>
   */
  public com.google.protobuf.ByteString
      getInitializerExprBytes() {
    java.lang.Object ref = "";
    if (optionalInitializerCase_ == 3) {
      ref = optionalInitializer_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (optionalInitializerCase_ == 3) {
        optionalInitializer_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFORM_EXPR_FIELD_NUMBER = 4;
  private volatile java.lang.Object transformExpr_;
  /**
   * <code>string transform_expr = 4;</code>
   */
  public java.lang.String getTransformExpr() {
    java.lang.Object ref = transformExpr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transformExpr_ = s;
      return s;
    }
  }
  /**
   * <code>string transform_expr = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTransformExprBytes() {
    java.lang.Object ref = transformExpr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transformExpr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMPORTED_CLASSES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList importedClasses_;
  /**
   * <code>repeated string imported_classes = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getImportedClassesList() {
    return importedClasses_;
  }
  /**
   * <code>repeated string imported_classes = 5;</code>
   */
  public int getImportedClassesCount() {
    return importedClasses_.size();
  }
  /**
   * <code>repeated string imported_classes = 5;</code>
   */
  public java.lang.String getImportedClasses(int index) {
    return importedClasses_.get(index);
  }
  /**
   * <code>repeated string imported_classes = 5;</code>
   */
  public com.google.protobuf.ByteString
      getImportedClassesBytes(int index) {
    return importedClasses_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (optionalOutputRecordSchemaCase_ == 1) {
      output.writeMessage(1, (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_);
    }
    if (optionalAddedRecordSchemaCase_ == 2) {
      output.writeMessage(2, (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_);
    }
    if (optionalInitializerCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, optionalInitializer_);
    }
    if (!getTransformExprBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, transformExpr_);
    }
    for (int i = 0; i < importedClasses_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, importedClasses_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (optionalOutputRecordSchemaCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_);
    }
    if (optionalAddedRecordSchemaCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_);
    }
    if (optionalInitializerCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, optionalInitializer_);
    }
    if (!getTransformExprBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, transformExpr_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < importedClasses_.size(); i++) {
        dataSize += computeStringSizeNoTag(importedClasses_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImportedClassesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.ScriptRecordTransformProto)) {
      return super.equals(obj);
    }
    marmot.proto.ScriptRecordTransformProto other = (marmot.proto.ScriptRecordTransformProto) obj;

    boolean result = true;
    result = result && getTransformExpr()
        .equals(other.getTransformExpr());
    result = result && getImportedClassesList()
        .equals(other.getImportedClassesList());
    result = result && getOptionalOutputRecordSchemaCase().equals(
        other.getOptionalOutputRecordSchemaCase());
    if (!result) return false;
    switch (optionalOutputRecordSchemaCase_) {
      case 1:
        result = result && getOutputRecordSchema()
            .equals(other.getOutputRecordSchema());
        break;
      case 0:
      default:
    }
    result = result && getOptionalAddedRecordSchemaCase().equals(
        other.getOptionalAddedRecordSchemaCase());
    if (!result) return false;
    switch (optionalAddedRecordSchemaCase_) {
      case 2:
        result = result && getAddedRecordSchema()
            .equals(other.getAddedRecordSchema());
        break;
      case 0:
      default:
    }
    result = result && getOptionalInitializerCase().equals(
        other.getOptionalInitializerCase());
    if (!result) return false;
    switch (optionalInitializerCase_) {
      case 3:
        result = result && getInitializerExpr()
            .equals(other.getInitializerExpr());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSFORM_EXPR_FIELD_NUMBER;
    hash = (53 * hash) + getTransformExpr().hashCode();
    if (getImportedClassesCount() > 0) {
      hash = (37 * hash) + IMPORTED_CLASSES_FIELD_NUMBER;
      hash = (53 * hash) + getImportedClassesList().hashCode();
    }
    switch (optionalOutputRecordSchemaCase_) {
      case 1:
        hash = (37 * hash) + OUTPUT_RECORD_SCHEMA_FIELD_NUMBER;
        hash = (53 * hash) + getOutputRecordSchema().hashCode();
        break;
      case 0:
      default:
    }
    switch (optionalAddedRecordSchemaCase_) {
      case 2:
        hash = (37 * hash) + ADDED_RECORD_SCHEMA_FIELD_NUMBER;
        hash = (53 * hash) + getAddedRecordSchema().hashCode();
        break;
      case 0:
      default:
    }
    switch (optionalInitializerCase_) {
      case 3:
        hash = (37 * hash) + INITIALIZER_EXPR_FIELD_NUMBER;
        hash = (53 * hash) + getInitializerExpr().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.ScriptRecordTransformProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.ScriptRecordTransformProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.ScriptRecordTransformProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.ScriptRecordTransformProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marmot.optor.proto.ScriptRecordTransformProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.optor.proto.ScriptRecordTransformProto)
      marmot.proto.ScriptRecordTransformProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.MarmotInternal.internal_static_marmot_optor_proto_ScriptRecordTransformProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.MarmotInternal.internal_static_marmot_optor_proto_ScriptRecordTransformProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.ScriptRecordTransformProto.class, marmot.proto.ScriptRecordTransformProto.Builder.class);
    }

    // Construct using marmot.proto.ScriptRecordTransformProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      transformExpr_ = "";

      importedClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      optionalOutputRecordSchemaCase_ = 0;
      optionalOutputRecordSchema_ = null;
      optionalAddedRecordSchemaCase_ = 0;
      optionalAddedRecordSchema_ = null;
      optionalInitializerCase_ = 0;
      optionalInitializer_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.MarmotInternal.internal_static_marmot_optor_proto_ScriptRecordTransformProto_descriptor;
    }

    public marmot.proto.ScriptRecordTransformProto getDefaultInstanceForType() {
      return marmot.proto.ScriptRecordTransformProto.getDefaultInstance();
    }

    public marmot.proto.ScriptRecordTransformProto build() {
      marmot.proto.ScriptRecordTransformProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.ScriptRecordTransformProto buildPartial() {
      marmot.proto.ScriptRecordTransformProto result = new marmot.proto.ScriptRecordTransformProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (optionalOutputRecordSchemaCase_ == 1) {
        if (outputRecordSchemaBuilder_ == null) {
          result.optionalOutputRecordSchema_ = optionalOutputRecordSchema_;
        } else {
          result.optionalOutputRecordSchema_ = outputRecordSchemaBuilder_.build();
        }
      }
      if (optionalAddedRecordSchemaCase_ == 2) {
        if (addedRecordSchemaBuilder_ == null) {
          result.optionalAddedRecordSchema_ = optionalAddedRecordSchema_;
        } else {
          result.optionalAddedRecordSchema_ = addedRecordSchemaBuilder_.build();
        }
      }
      if (optionalInitializerCase_ == 3) {
        result.optionalInitializer_ = optionalInitializer_;
      }
      result.transformExpr_ = transformExpr_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        importedClasses_ = importedClasses_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.importedClasses_ = importedClasses_;
      result.bitField0_ = to_bitField0_;
      result.optionalOutputRecordSchemaCase_ = optionalOutputRecordSchemaCase_;
      result.optionalAddedRecordSchemaCase_ = optionalAddedRecordSchemaCase_;
      result.optionalInitializerCase_ = optionalInitializerCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.ScriptRecordTransformProto) {
        return mergeFrom((marmot.proto.ScriptRecordTransformProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.ScriptRecordTransformProto other) {
      if (other == marmot.proto.ScriptRecordTransformProto.getDefaultInstance()) return this;
      if (!other.getTransformExpr().isEmpty()) {
        transformExpr_ = other.transformExpr_;
        onChanged();
      }
      if (!other.importedClasses_.isEmpty()) {
        if (importedClasses_.isEmpty()) {
          importedClasses_ = other.importedClasses_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureImportedClassesIsMutable();
          importedClasses_.addAll(other.importedClasses_);
        }
        onChanged();
      }
      switch (other.getOptionalOutputRecordSchemaCase()) {
        case OUTPUT_RECORD_SCHEMA: {
          mergeOutputRecordSchema(other.getOutputRecordSchema());
          break;
        }
        case OPTIONALOUTPUTRECORDSCHEMA_NOT_SET: {
          break;
        }
      }
      switch (other.getOptionalAddedRecordSchemaCase()) {
        case ADDED_RECORD_SCHEMA: {
          mergeAddedRecordSchema(other.getAddedRecordSchema());
          break;
        }
        case OPTIONALADDEDRECORDSCHEMA_NOT_SET: {
          break;
        }
      }
      switch (other.getOptionalInitializerCase()) {
        case INITIALIZER_EXPR: {
          optionalInitializerCase_ = 3;
          optionalInitializer_ = other.optionalInitializer_;
          onChanged();
          break;
        }
        case OPTIONALINITIALIZER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.ScriptRecordTransformProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.ScriptRecordTransformProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int optionalOutputRecordSchemaCase_ = 0;
    private java.lang.Object optionalOutputRecordSchema_;
    public OptionalOutputRecordSchemaCase
        getOptionalOutputRecordSchemaCase() {
      return OptionalOutputRecordSchemaCase.forNumber(
          optionalOutputRecordSchemaCase_);
    }

    public Builder clearOptionalOutputRecordSchema() {
      optionalOutputRecordSchemaCase_ = 0;
      optionalOutputRecordSchema_ = null;
      onChanged();
      return this;
    }

    private int optionalAddedRecordSchemaCase_ = 0;
    private java.lang.Object optionalAddedRecordSchema_;
    public OptionalAddedRecordSchemaCase
        getOptionalAddedRecordSchemaCase() {
      return OptionalAddedRecordSchemaCase.forNumber(
          optionalAddedRecordSchemaCase_);
    }

    public Builder clearOptionalAddedRecordSchema() {
      optionalAddedRecordSchemaCase_ = 0;
      optionalAddedRecordSchema_ = null;
      onChanged();
      return this;
    }

    private int optionalInitializerCase_ = 0;
    private java.lang.Object optionalInitializer_;
    public OptionalInitializerCase
        getOptionalInitializerCase() {
      return OptionalInitializerCase.forNumber(
          optionalInitializerCase_);
    }

    public Builder clearOptionalInitializer() {
      optionalInitializerCase_ = 0;
      optionalInitializer_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> outputRecordSchemaBuilder_;
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public boolean hasOutputRecordSchema() {
      return optionalOutputRecordSchemaCase_ == 1;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public marmot.proto.RecordSchemaProto getOutputRecordSchema() {
      if (outputRecordSchemaBuilder_ == null) {
        if (optionalOutputRecordSchemaCase_ == 1) {
          return (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_;
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      } else {
        if (optionalOutputRecordSchemaCase_ == 1) {
          return outputRecordSchemaBuilder_.getMessage();
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public Builder setOutputRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (outputRecordSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        optionalOutputRecordSchema_ = value;
        onChanged();
      } else {
        outputRecordSchemaBuilder_.setMessage(value);
      }
      optionalOutputRecordSchemaCase_ = 1;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public Builder setOutputRecordSchema(
        marmot.proto.RecordSchemaProto.Builder builderForValue) {
      if (outputRecordSchemaBuilder_ == null) {
        optionalOutputRecordSchema_ = builderForValue.build();
        onChanged();
      } else {
        outputRecordSchemaBuilder_.setMessage(builderForValue.build());
      }
      optionalOutputRecordSchemaCase_ = 1;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public Builder mergeOutputRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (outputRecordSchemaBuilder_ == null) {
        if (optionalOutputRecordSchemaCase_ == 1 &&
            optionalOutputRecordSchema_ != marmot.proto.RecordSchemaProto.getDefaultInstance()) {
          optionalOutputRecordSchema_ = marmot.proto.RecordSchemaProto.newBuilder((marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_)
              .mergeFrom(value).buildPartial();
        } else {
          optionalOutputRecordSchema_ = value;
        }
        onChanged();
      } else {
        if (optionalOutputRecordSchemaCase_ == 1) {
          outputRecordSchemaBuilder_.mergeFrom(value);
        }
        outputRecordSchemaBuilder_.setMessage(value);
      }
      optionalOutputRecordSchemaCase_ = 1;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public Builder clearOutputRecordSchema() {
      if (outputRecordSchemaBuilder_ == null) {
        if (optionalOutputRecordSchemaCase_ == 1) {
          optionalOutputRecordSchemaCase_ = 0;
          optionalOutputRecordSchema_ = null;
          onChanged();
        }
      } else {
        if (optionalOutputRecordSchemaCase_ == 1) {
          optionalOutputRecordSchemaCase_ = 0;
          optionalOutputRecordSchema_ = null;
        }
        outputRecordSchemaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public marmot.proto.RecordSchemaProto.Builder getOutputRecordSchemaBuilder() {
      return getOutputRecordSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    public marmot.proto.RecordSchemaProtoOrBuilder getOutputRecordSchemaOrBuilder() {
      if ((optionalOutputRecordSchemaCase_ == 1) && (outputRecordSchemaBuilder_ != null)) {
        return outputRecordSchemaBuilder_.getMessageOrBuilder();
      } else {
        if (optionalOutputRecordSchemaCase_ == 1) {
          return (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_;
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto output_record_schema = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> 
        getOutputRecordSchemaFieldBuilder() {
      if (outputRecordSchemaBuilder_ == null) {
        if (!(optionalOutputRecordSchemaCase_ == 1)) {
          optionalOutputRecordSchema_ = marmot.proto.RecordSchemaProto.getDefaultInstance();
        }
        outputRecordSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder>(
                (marmot.proto.RecordSchemaProto) optionalOutputRecordSchema_,
                getParentForChildren(),
                isClean());
        optionalOutputRecordSchema_ = null;
      }
      optionalOutputRecordSchemaCase_ = 1;
      onChanged();;
      return outputRecordSchemaBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> addedRecordSchemaBuilder_;
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public boolean hasAddedRecordSchema() {
      return optionalAddedRecordSchemaCase_ == 2;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public marmot.proto.RecordSchemaProto getAddedRecordSchema() {
      if (addedRecordSchemaBuilder_ == null) {
        if (optionalAddedRecordSchemaCase_ == 2) {
          return (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_;
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      } else {
        if (optionalAddedRecordSchemaCase_ == 2) {
          return addedRecordSchemaBuilder_.getMessage();
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public Builder setAddedRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (addedRecordSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        optionalAddedRecordSchema_ = value;
        onChanged();
      } else {
        addedRecordSchemaBuilder_.setMessage(value);
      }
      optionalAddedRecordSchemaCase_ = 2;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public Builder setAddedRecordSchema(
        marmot.proto.RecordSchemaProto.Builder builderForValue) {
      if (addedRecordSchemaBuilder_ == null) {
        optionalAddedRecordSchema_ = builderForValue.build();
        onChanged();
      } else {
        addedRecordSchemaBuilder_.setMessage(builderForValue.build());
      }
      optionalAddedRecordSchemaCase_ = 2;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public Builder mergeAddedRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (addedRecordSchemaBuilder_ == null) {
        if (optionalAddedRecordSchemaCase_ == 2 &&
            optionalAddedRecordSchema_ != marmot.proto.RecordSchemaProto.getDefaultInstance()) {
          optionalAddedRecordSchema_ = marmot.proto.RecordSchemaProto.newBuilder((marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_)
              .mergeFrom(value).buildPartial();
        } else {
          optionalAddedRecordSchema_ = value;
        }
        onChanged();
      } else {
        if (optionalAddedRecordSchemaCase_ == 2) {
          addedRecordSchemaBuilder_.mergeFrom(value);
        }
        addedRecordSchemaBuilder_.setMessage(value);
      }
      optionalAddedRecordSchemaCase_ = 2;
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public Builder clearAddedRecordSchema() {
      if (addedRecordSchemaBuilder_ == null) {
        if (optionalAddedRecordSchemaCase_ == 2) {
          optionalAddedRecordSchemaCase_ = 0;
          optionalAddedRecordSchema_ = null;
          onChanged();
        }
      } else {
        if (optionalAddedRecordSchemaCase_ == 2) {
          optionalAddedRecordSchemaCase_ = 0;
          optionalAddedRecordSchema_ = null;
        }
        addedRecordSchemaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public marmot.proto.RecordSchemaProto.Builder getAddedRecordSchemaBuilder() {
      return getAddedRecordSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    public marmot.proto.RecordSchemaProtoOrBuilder getAddedRecordSchemaOrBuilder() {
      if ((optionalAddedRecordSchemaCase_ == 2) && (addedRecordSchemaBuilder_ != null)) {
        return addedRecordSchemaBuilder_.getMessageOrBuilder();
      } else {
        if (optionalAddedRecordSchemaCase_ == 2) {
          return (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_;
        }
        return marmot.proto.RecordSchemaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto added_record_schema = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> 
        getAddedRecordSchemaFieldBuilder() {
      if (addedRecordSchemaBuilder_ == null) {
        if (!(optionalAddedRecordSchemaCase_ == 2)) {
          optionalAddedRecordSchema_ = marmot.proto.RecordSchemaProto.getDefaultInstance();
        }
        addedRecordSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder>(
                (marmot.proto.RecordSchemaProto) optionalAddedRecordSchema_,
                getParentForChildren(),
                isClean());
        optionalAddedRecordSchema_ = null;
      }
      optionalAddedRecordSchemaCase_ = 2;
      onChanged();;
      return addedRecordSchemaBuilder_;
    }

    /**
     * <code>string initializer_expr = 3;</code>
     */
    public java.lang.String getInitializerExpr() {
      java.lang.Object ref = "";
      if (optionalInitializerCase_ == 3) {
        ref = optionalInitializer_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (optionalInitializerCase_ == 3) {
          optionalInitializer_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string initializer_expr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInitializerExprBytes() {
      java.lang.Object ref = "";
      if (optionalInitializerCase_ == 3) {
        ref = optionalInitializer_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (optionalInitializerCase_ == 3) {
          optionalInitializer_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string initializer_expr = 3;</code>
     */
    public Builder setInitializerExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  optionalInitializerCase_ = 3;
      optionalInitializer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string initializer_expr = 3;</code>
     */
    public Builder clearInitializerExpr() {
      if (optionalInitializerCase_ == 3) {
        optionalInitializerCase_ = 0;
        optionalInitializer_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string initializer_expr = 3;</code>
     */
    public Builder setInitializerExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      optionalInitializerCase_ = 3;
      optionalInitializer_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transformExpr_ = "";
    /**
     * <code>string transform_expr = 4;</code>
     */
    public java.lang.String getTransformExpr() {
      java.lang.Object ref = transformExpr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transformExpr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transform_expr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTransformExprBytes() {
      java.lang.Object ref = transformExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transformExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transform_expr = 4;</code>
     */
    public Builder setTransformExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transformExpr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transform_expr = 4;</code>
     */
    public Builder clearTransformExpr() {
      
      transformExpr_ = getDefaultInstance().getTransformExpr();
      onChanged();
      return this;
    }
    /**
     * <code>string transform_expr = 4;</code>
     */
    public Builder setTransformExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transformExpr_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList importedClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImportedClassesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        importedClasses_ = new com.google.protobuf.LazyStringArrayList(importedClasses_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getImportedClassesList() {
      return importedClasses_.getUnmodifiableView();
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public int getImportedClassesCount() {
      return importedClasses_.size();
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public java.lang.String getImportedClasses(int index) {
      return importedClasses_.get(index);
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImportedClassesBytes(int index) {
      return importedClasses_.getByteString(index);
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public Builder setImportedClasses(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImportedClassesIsMutable();
      importedClasses_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public Builder addImportedClasses(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImportedClassesIsMutable();
      importedClasses_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public Builder addAllImportedClasses(
        java.lang.Iterable<java.lang.String> values) {
      ensureImportedClassesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, importedClasses_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public Builder clearImportedClasses() {
      importedClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string imported_classes = 5;</code>
     */
    public Builder addImportedClassesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureImportedClassesIsMutable();
      importedClasses_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.optor.proto.ScriptRecordTransformProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.optor.proto.ScriptRecordTransformProto)
  private static final marmot.proto.ScriptRecordTransformProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.ScriptRecordTransformProto();
  }

  public static marmot.proto.ScriptRecordTransformProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScriptRecordTransformProto>
      PARSER = new com.google.protobuf.AbstractParser<ScriptRecordTransformProto>() {
    public ScriptRecordTransformProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScriptRecordTransformProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScriptRecordTransformProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScriptRecordTransformProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.ScriptRecordTransformProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

