// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface AggregateIntermAtMapSideProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.AggregateIntermAtMapSideProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.marmot.proto.SerializedProto reducer = 1;</code>
   */
  boolean hasReducer();
  /**
   * <code>.marmot.proto.SerializedProto reducer = 1;</code>
   */
  marmot.proto.SerializedProto getReducer();
  /**
   * <code>.marmot.proto.SerializedProto reducer = 1;</code>
   */
  marmot.proto.SerializedProtoOrBuilder getReducerOrBuilder();
}
