// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface CalcLocalMoransIProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.CalcLocalMoransIProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataset = 1;</code>
   */
  java.lang.String getDataset();
  /**
   * <code>string dataset = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatasetBytes();

  /**
   * <code>string geometry_column = 2;</code>
   */
  java.lang.String getGeometryColumn();
  /**
   * <code>string geometry_column = 2;</code>
   */
  com.google.protobuf.ByteString
      getGeometryColumnBytes();

  /**
   * <code>string value_column = 3;</code>
   */
  java.lang.String getValueColumn();
  /**
   * <code>string value_column = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueColumnBytes();

  /**
   * <code>string id_column = 4;</code>
   */
  java.lang.String getIdColumn();
  /**
   * <code>string id_column = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdColumnBytes();

  /**
   * <code>double radius = 5;</code>
   */
  double getRadius();

  /**
   * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
   */
  int getWeightTypeValue();
  /**
   * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
   */
  marmot.proto.optor.LISAWeightProto getWeightType();

  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  boolean hasParameters();
  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  marmot.proto.optor.LISAParametersProto getParameters();
  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  marmot.proto.optor.LISAParametersProtoOrBuilder getParametersOrBuilder();
}
