// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * <pre>
 * Local Morans'I
 * </pre>
 *
 * Protobuf type {@code marmot.proto.optor.CalcLocalMoransIProto}
 */
public  final class CalcLocalMoransIProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.CalcLocalMoransIProto)
    CalcLocalMoransIProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalcLocalMoransIProto.newBuilder() to construct.
  private CalcLocalMoransIProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalcLocalMoransIProto() {
    dataset_ = "";
    geometryColumn_ = "";
    valueColumn_ = "";
    idColumn_ = "";
    radius_ = 0D;
    weightType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalcLocalMoransIProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dataset_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            geometryColumn_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            valueColumn_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            idColumn_ = s;
            break;
          }
          case 41: {

            radius_ = input.readDouble();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            weightType_ = rawValue;
            break;
          }
          case 58: {
            marmot.proto.optor.LISAParametersProto.Builder subBuilder = null;
            if (parameters_ != null) {
              subBuilder = parameters_.toBuilder();
            }
            parameters_ = input.readMessage(marmot.proto.optor.LISAParametersProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(parameters_);
              parameters_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcLocalMoransIProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.CalcLocalMoransIProto.class, marmot.proto.optor.CalcLocalMoransIProto.Builder.class);
  }

  public static final int DATASET_FIELD_NUMBER = 1;
  private volatile java.lang.Object dataset_;
  /**
   * <code>string dataset = 1;</code>
   */
  public java.lang.String getDataset() {
    java.lang.Object ref = dataset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataset_ = s;
      return s;
    }
  }
  /**
   * <code>string dataset = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDatasetBytes() {
    java.lang.Object ref = dataset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GEOMETRY_COLUMN_FIELD_NUMBER = 2;
  private volatile java.lang.Object geometryColumn_;
  /**
   * <code>string geometry_column = 2;</code>
   */
  public java.lang.String getGeometryColumn() {
    java.lang.Object ref = geometryColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      geometryColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string geometry_column = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGeometryColumnBytes() {
    java.lang.Object ref = geometryColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      geometryColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_COLUMN_FIELD_NUMBER = 3;
  private volatile java.lang.Object valueColumn_;
  /**
   * <code>string value_column = 3;</code>
   */
  public java.lang.String getValueColumn() {
    java.lang.Object ref = valueColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      valueColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string value_column = 3;</code>
   */
  public com.google.protobuf.ByteString
      getValueColumnBytes() {
    java.lang.Object ref = valueColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      valueColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_COLUMN_FIELD_NUMBER = 4;
  private volatile java.lang.Object idColumn_;
  /**
   * <code>string id_column = 4;</code>
   */
  public java.lang.String getIdColumn() {
    java.lang.Object ref = idColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string id_column = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIdColumnBytes() {
    java.lang.Object ref = idColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RADIUS_FIELD_NUMBER = 5;
  private double radius_;
  /**
   * <code>double radius = 5;</code>
   */
  public double getRadius() {
    return radius_;
  }

  public static final int WEIGHT_TYPE_FIELD_NUMBER = 6;
  private int weightType_;
  /**
   * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
   */
  public int getWeightTypeValue() {
    return weightType_;
  }
  /**
   * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
   */
  public marmot.proto.optor.LISAWeightProto getWeightType() {
    marmot.proto.optor.LISAWeightProto result = marmot.proto.optor.LISAWeightProto.valueOf(weightType_);
    return result == null ? marmot.proto.optor.LISAWeightProto.UNRECOGNIZED : result;
  }

  public static final int PARAMETERS_FIELD_NUMBER = 7;
  private marmot.proto.optor.LISAParametersProto parameters_;
  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  public boolean hasParameters() {
    return parameters_ != null;
  }
  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  public marmot.proto.optor.LISAParametersProto getParameters() {
    return parameters_ == null ? marmot.proto.optor.LISAParametersProto.getDefaultInstance() : parameters_;
  }
  /**
   * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
   */
  public marmot.proto.optor.LISAParametersProtoOrBuilder getParametersOrBuilder() {
    return getParameters();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDatasetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataset_);
    }
    if (!getGeometryColumnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, geometryColumn_);
    }
    if (!getValueColumnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, valueColumn_);
    }
    if (!getIdColumnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, idColumn_);
    }
    if (radius_ != 0D) {
      output.writeDouble(5, radius_);
    }
    if (weightType_ != marmot.proto.optor.LISAWeightProto.FIXED_DISTANCE_BAND.getNumber()) {
      output.writeEnum(6, weightType_);
    }
    if (parameters_ != null) {
      output.writeMessage(7, getParameters());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDatasetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataset_);
    }
    if (!getGeometryColumnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, geometryColumn_);
    }
    if (!getValueColumnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, valueColumn_);
    }
    if (!getIdColumnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, idColumn_);
    }
    if (radius_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, radius_);
    }
    if (weightType_ != marmot.proto.optor.LISAWeightProto.FIXED_DISTANCE_BAND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, weightType_);
    }
    if (parameters_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getParameters());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.CalcLocalMoransIProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.CalcLocalMoransIProto other = (marmot.proto.optor.CalcLocalMoransIProto) obj;

    boolean result = true;
    result = result && getDataset()
        .equals(other.getDataset());
    result = result && getGeometryColumn()
        .equals(other.getGeometryColumn());
    result = result && getValueColumn()
        .equals(other.getValueColumn());
    result = result && getIdColumn()
        .equals(other.getIdColumn());
    result = result && (
        java.lang.Double.doubleToLongBits(getRadius())
        == java.lang.Double.doubleToLongBits(
            other.getRadius()));
    result = result && weightType_ == other.weightType_;
    result = result && (hasParameters() == other.hasParameters());
    if (hasParameters()) {
      result = result && getParameters()
          .equals(other.getParameters());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASET_FIELD_NUMBER;
    hash = (53 * hash) + getDataset().hashCode();
    hash = (37 * hash) + GEOMETRY_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getGeometryColumn().hashCode();
    hash = (37 * hash) + VALUE_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getValueColumn().hashCode();
    hash = (37 * hash) + ID_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getIdColumn().hashCode();
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRadius()));
    hash = (37 * hash) + WEIGHT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + weightType_;
    if (hasParameters()) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParameters().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcLocalMoransIProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.CalcLocalMoransIProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Local Morans'I
   * </pre>
   *
   * Protobuf type {@code marmot.proto.optor.CalcLocalMoransIProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.CalcLocalMoransIProto)
      marmot.proto.optor.CalcLocalMoransIProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcLocalMoransIProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.CalcLocalMoransIProto.class, marmot.proto.optor.CalcLocalMoransIProto.Builder.class);
    }

    // Construct using marmot.proto.optor.CalcLocalMoransIProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dataset_ = "";

      geometryColumn_ = "";

      valueColumn_ = "";

      idColumn_ = "";

      radius_ = 0D;

      weightType_ = 0;

      if (parametersBuilder_ == null) {
        parameters_ = null;
      } else {
        parameters_ = null;
        parametersBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor;
    }

    public marmot.proto.optor.CalcLocalMoransIProto getDefaultInstanceForType() {
      return marmot.proto.optor.CalcLocalMoransIProto.getDefaultInstance();
    }

    public marmot.proto.optor.CalcLocalMoransIProto build() {
      marmot.proto.optor.CalcLocalMoransIProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.CalcLocalMoransIProto buildPartial() {
      marmot.proto.optor.CalcLocalMoransIProto result = new marmot.proto.optor.CalcLocalMoransIProto(this);
      result.dataset_ = dataset_;
      result.geometryColumn_ = geometryColumn_;
      result.valueColumn_ = valueColumn_;
      result.idColumn_ = idColumn_;
      result.radius_ = radius_;
      result.weightType_ = weightType_;
      if (parametersBuilder_ == null) {
        result.parameters_ = parameters_;
      } else {
        result.parameters_ = parametersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.CalcLocalMoransIProto) {
        return mergeFrom((marmot.proto.optor.CalcLocalMoransIProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.CalcLocalMoransIProto other) {
      if (other == marmot.proto.optor.CalcLocalMoransIProto.getDefaultInstance()) return this;
      if (!other.getDataset().isEmpty()) {
        dataset_ = other.dataset_;
        onChanged();
      }
      if (!other.getGeometryColumn().isEmpty()) {
        geometryColumn_ = other.geometryColumn_;
        onChanged();
      }
      if (!other.getValueColumn().isEmpty()) {
        valueColumn_ = other.valueColumn_;
        onChanged();
      }
      if (!other.getIdColumn().isEmpty()) {
        idColumn_ = other.idColumn_;
        onChanged();
      }
      if (other.getRadius() != 0D) {
        setRadius(other.getRadius());
      }
      if (other.weightType_ != 0) {
        setWeightTypeValue(other.getWeightTypeValue());
      }
      if (other.hasParameters()) {
        mergeParameters(other.getParameters());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.CalcLocalMoransIProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.CalcLocalMoransIProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dataset_ = "";
    /**
     * <code>string dataset = 1;</code>
     */
    public java.lang.String getDataset() {
      java.lang.Object ref = dataset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatasetBytes() {
      java.lang.Object ref = dataset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder setDataset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder clearDataset() {
      
      dataset_ = getDefaultInstance().getDataset();
      onChanged();
      return this;
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder setDatasetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataset_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object geometryColumn_ = "";
    /**
     * <code>string geometry_column = 2;</code>
     */
    public java.lang.String getGeometryColumn() {
      java.lang.Object ref = geometryColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        geometryColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGeometryColumnBytes() {
      java.lang.Object ref = geometryColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        geometryColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder setGeometryColumn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      geometryColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder clearGeometryColumn() {
      
      geometryColumn_ = getDefaultInstance().getGeometryColumn();
      onChanged();
      return this;
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder setGeometryColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      geometryColumn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object valueColumn_ = "";
    /**
     * <code>string value_column = 3;</code>
     */
    public java.lang.String getValueColumn() {
      java.lang.Object ref = valueColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value_column = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueColumnBytes() {
      java.lang.Object ref = valueColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value_column = 3;</code>
     */
    public Builder setValueColumn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      valueColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value_column = 3;</code>
     */
    public Builder clearValueColumn() {
      
      valueColumn_ = getDefaultInstance().getValueColumn();
      onChanged();
      return this;
    }
    /**
     * <code>string value_column = 3;</code>
     */
    public Builder setValueColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      valueColumn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object idColumn_ = "";
    /**
     * <code>string id_column = 4;</code>
     */
    public java.lang.String getIdColumn() {
      java.lang.Object ref = idColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id_column = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdColumnBytes() {
      java.lang.Object ref = idColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id_column = 4;</code>
     */
    public Builder setIdColumn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id_column = 4;</code>
     */
    public Builder clearIdColumn() {
      
      idColumn_ = getDefaultInstance().getIdColumn();
      onChanged();
      return this;
    }
    /**
     * <code>string id_column = 4;</code>
     */
    public Builder setIdColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idColumn_ = value;
      onChanged();
      return this;
    }

    private double radius_ ;
    /**
     * <code>double radius = 5;</code>
     */
    public double getRadius() {
      return radius_;
    }
    /**
     * <code>double radius = 5;</code>
     */
    public Builder setRadius(double value) {
      
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double radius = 5;</code>
     */
    public Builder clearRadius() {
      
      radius_ = 0D;
      onChanged();
      return this;
    }

    private int weightType_ = 0;
    /**
     * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
     */
    public int getWeightTypeValue() {
      return weightType_;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
     */
    public Builder setWeightTypeValue(int value) {
      weightType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
     */
    public marmot.proto.optor.LISAWeightProto getWeightType() {
      marmot.proto.optor.LISAWeightProto result = marmot.proto.optor.LISAWeightProto.valueOf(weightType_);
      return result == null ? marmot.proto.optor.LISAWeightProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
     */
    public Builder setWeightType(marmot.proto.optor.LISAWeightProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      weightType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto weight_type = 6;</code>
     */
    public Builder clearWeightType() {
      
      weightType_ = 0;
      onChanged();
      return this;
    }

    private marmot.proto.optor.LISAParametersProto parameters_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.optor.LISAParametersProto, marmot.proto.optor.LISAParametersProto.Builder, marmot.proto.optor.LISAParametersProtoOrBuilder> parametersBuilder_;
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public boolean hasParameters() {
      return parametersBuilder_ != null || parameters_ != null;
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public marmot.proto.optor.LISAParametersProto getParameters() {
      if (parametersBuilder_ == null) {
        return parameters_ == null ? marmot.proto.optor.LISAParametersProto.getDefaultInstance() : parameters_;
      } else {
        return parametersBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public Builder setParameters(marmot.proto.optor.LISAParametersProto value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parameters_ = value;
        onChanged();
      } else {
        parametersBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public Builder setParameters(
        marmot.proto.optor.LISAParametersProto.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        parameters_ = builderForValue.build();
        onChanged();
      } else {
        parametersBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public Builder mergeParameters(marmot.proto.optor.LISAParametersProto value) {
      if (parametersBuilder_ == null) {
        if (parameters_ != null) {
          parameters_ =
            marmot.proto.optor.LISAParametersProto.newBuilder(parameters_).mergeFrom(value).buildPartial();
        } else {
          parameters_ = value;
        }
        onChanged();
      } else {
        parametersBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public Builder clearParameters() {
      if (parametersBuilder_ == null) {
        parameters_ = null;
        onChanged();
      } else {
        parameters_ = null;
        parametersBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public marmot.proto.optor.LISAParametersProto.Builder getParametersBuilder() {
      
      onChanged();
      return getParametersFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    public marmot.proto.optor.LISAParametersProtoOrBuilder getParametersOrBuilder() {
      if (parametersBuilder_ != null) {
        return parametersBuilder_.getMessageOrBuilder();
      } else {
        return parameters_ == null ?
            marmot.proto.optor.LISAParametersProto.getDefaultInstance() : parameters_;
      }
    }
    /**
     * <code>.marmot.proto.optor.LISAParametersProto parameters = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.optor.LISAParametersProto, marmot.proto.optor.LISAParametersProto.Builder, marmot.proto.optor.LISAParametersProtoOrBuilder> 
        getParametersFieldBuilder() {
      if (parametersBuilder_ == null) {
        parametersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.optor.LISAParametersProto, marmot.proto.optor.LISAParametersProto.Builder, marmot.proto.optor.LISAParametersProtoOrBuilder>(
                getParameters(),
                getParentForChildren(),
                isClean());
        parameters_ = null;
      }
      return parametersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.CalcLocalMoransIProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.CalcLocalMoransIProto)
  private static final marmot.proto.optor.CalcLocalMoransIProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.CalcLocalMoransIProto();
  }

  public static marmot.proto.optor.CalcLocalMoransIProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalcLocalMoransIProto>
      PARSER = new com.google.protobuf.AbstractParser<CalcLocalMoransIProto>() {
    public CalcLocalMoransIProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalcLocalMoransIProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalcLocalMoransIProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalcLocalMoransIProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.CalcLocalMoransIProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

