// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * <pre>
 * Global Morans'I
 * </pre>
 *
 * Protobuf type {@code marmot.proto.optor.CalcGlobalMoranIIntermediateProto}
 */
public  final class CalcGlobalMoranIIntermediateProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.CalcGlobalMoranIIntermediateProto)
    CalcGlobalMoranIIntermediateProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalcGlobalMoranIIntermediateProto.newBuilder() to construct.
  private CalcGlobalMoranIIntermediateProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalcGlobalMoranIIntermediateProto() {
    dataset_ = "";
    geometryColumn_ = "";
    targetColumn_ = "";
    radius_ = 0D;
    wtype_ = 0;
    average_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalcGlobalMoranIIntermediateProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dataset_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            geometryColumn_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            targetColumn_ = s;
            break;
          }
          case 33: {

            radius_ = input.readDouble();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            wtype_ = rawValue;
            break;
          }
          case 49: {

            average_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.CalcGlobalMoranIIntermediateProto.class, marmot.proto.optor.CalcGlobalMoranIIntermediateProto.Builder.class);
  }

  public static final int DATASET_FIELD_NUMBER = 1;
  private volatile java.lang.Object dataset_;
  /**
   * <code>string dataset = 1;</code>
   */
  public java.lang.String getDataset() {
    java.lang.Object ref = dataset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataset_ = s;
      return s;
    }
  }
  /**
   * <code>string dataset = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDatasetBytes() {
    java.lang.Object ref = dataset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GEOMETRY_COLUMN_FIELD_NUMBER = 2;
  private volatile java.lang.Object geometryColumn_;
  /**
   * <code>string geometry_column = 2;</code>
   */
  public java.lang.String getGeometryColumn() {
    java.lang.Object ref = geometryColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      geometryColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string geometry_column = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGeometryColumnBytes() {
    java.lang.Object ref = geometryColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      geometryColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_COLUMN_FIELD_NUMBER = 3;
  private volatile java.lang.Object targetColumn_;
  /**
   * <code>string target_column = 3;</code>
   */
  public java.lang.String getTargetColumn() {
    java.lang.Object ref = targetColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string target_column = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTargetColumnBytes() {
    java.lang.Object ref = targetColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RADIUS_FIELD_NUMBER = 4;
  private double radius_;
  /**
   * <code>double radius = 4;</code>
   */
  public double getRadius() {
    return radius_;
  }

  public static final int WTYPE_FIELD_NUMBER = 5;
  private int wtype_;
  /**
   * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
   */
  public int getWtypeValue() {
    return wtype_;
  }
  /**
   * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
   */
  public marmot.proto.optor.LISAWeightProto getWtype() {
    marmot.proto.optor.LISAWeightProto result = marmot.proto.optor.LISAWeightProto.valueOf(wtype_);
    return result == null ? marmot.proto.optor.LISAWeightProto.UNRECOGNIZED : result;
  }

  public static final int AVERAGE_FIELD_NUMBER = 6;
  private double average_;
  /**
   * <code>double average = 6;</code>
   */
  public double getAverage() {
    return average_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDatasetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataset_);
    }
    if (!getGeometryColumnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, geometryColumn_);
    }
    if (!getTargetColumnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetColumn_);
    }
    if (radius_ != 0D) {
      output.writeDouble(4, radius_);
    }
    if (wtype_ != marmot.proto.optor.LISAWeightProto.FIXED_DISTANCE_BAND.getNumber()) {
      output.writeEnum(5, wtype_);
    }
    if (average_ != 0D) {
      output.writeDouble(6, average_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDatasetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataset_);
    }
    if (!getGeometryColumnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, geometryColumn_);
    }
    if (!getTargetColumnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, targetColumn_);
    }
    if (radius_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, radius_);
    }
    if (wtype_ != marmot.proto.optor.LISAWeightProto.FIXED_DISTANCE_BAND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, wtype_);
    }
    if (average_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, average_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.CalcGlobalMoranIIntermediateProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.CalcGlobalMoranIIntermediateProto other = (marmot.proto.optor.CalcGlobalMoranIIntermediateProto) obj;

    boolean result = true;
    result = result && getDataset()
        .equals(other.getDataset());
    result = result && getGeometryColumn()
        .equals(other.getGeometryColumn());
    result = result && getTargetColumn()
        .equals(other.getTargetColumn());
    result = result && (
        java.lang.Double.doubleToLongBits(getRadius())
        == java.lang.Double.doubleToLongBits(
            other.getRadius()));
    result = result && wtype_ == other.wtype_;
    result = result && (
        java.lang.Double.doubleToLongBits(getAverage())
        == java.lang.Double.doubleToLongBits(
            other.getAverage()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASET_FIELD_NUMBER;
    hash = (53 * hash) + getDataset().hashCode();
    hash = (37 * hash) + GEOMETRY_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getGeometryColumn().hashCode();
    hash = (37 * hash) + TARGET_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getTargetColumn().hashCode();
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRadius()));
    hash = (37 * hash) + WTYPE_FIELD_NUMBER;
    hash = (53 * hash) + wtype_;
    hash = (37 * hash) + AVERAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAverage()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.CalcGlobalMoranIIntermediateProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Global Morans'I
   * </pre>
   *
   * Protobuf type {@code marmot.proto.optor.CalcGlobalMoranIIntermediateProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.CalcGlobalMoranIIntermediateProto)
      marmot.proto.optor.CalcGlobalMoranIIntermediateProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.CalcGlobalMoranIIntermediateProto.class, marmot.proto.optor.CalcGlobalMoranIIntermediateProto.Builder.class);
    }

    // Construct using marmot.proto.optor.CalcGlobalMoranIIntermediateProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dataset_ = "";

      geometryColumn_ = "";

      targetColumn_ = "";

      radius_ = 0D;

      wtype_ = 0;

      average_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor;
    }

    public marmot.proto.optor.CalcGlobalMoranIIntermediateProto getDefaultInstanceForType() {
      return marmot.proto.optor.CalcGlobalMoranIIntermediateProto.getDefaultInstance();
    }

    public marmot.proto.optor.CalcGlobalMoranIIntermediateProto build() {
      marmot.proto.optor.CalcGlobalMoranIIntermediateProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.CalcGlobalMoranIIntermediateProto buildPartial() {
      marmot.proto.optor.CalcGlobalMoranIIntermediateProto result = new marmot.proto.optor.CalcGlobalMoranIIntermediateProto(this);
      result.dataset_ = dataset_;
      result.geometryColumn_ = geometryColumn_;
      result.targetColumn_ = targetColumn_;
      result.radius_ = radius_;
      result.wtype_ = wtype_;
      result.average_ = average_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.CalcGlobalMoranIIntermediateProto) {
        return mergeFrom((marmot.proto.optor.CalcGlobalMoranIIntermediateProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.CalcGlobalMoranIIntermediateProto other) {
      if (other == marmot.proto.optor.CalcGlobalMoranIIntermediateProto.getDefaultInstance()) return this;
      if (!other.getDataset().isEmpty()) {
        dataset_ = other.dataset_;
        onChanged();
      }
      if (!other.getGeometryColumn().isEmpty()) {
        geometryColumn_ = other.geometryColumn_;
        onChanged();
      }
      if (!other.getTargetColumn().isEmpty()) {
        targetColumn_ = other.targetColumn_;
        onChanged();
      }
      if (other.getRadius() != 0D) {
        setRadius(other.getRadius());
      }
      if (other.wtype_ != 0) {
        setWtypeValue(other.getWtypeValue());
      }
      if (other.getAverage() != 0D) {
        setAverage(other.getAverage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.CalcGlobalMoranIIntermediateProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.CalcGlobalMoranIIntermediateProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dataset_ = "";
    /**
     * <code>string dataset = 1;</code>
     */
    public java.lang.String getDataset() {
      java.lang.Object ref = dataset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatasetBytes() {
      java.lang.Object ref = dataset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder setDataset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder clearDataset() {
      
      dataset_ = getDefaultInstance().getDataset();
      onChanged();
      return this;
    }
    /**
     * <code>string dataset = 1;</code>
     */
    public Builder setDatasetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataset_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object geometryColumn_ = "";
    /**
     * <code>string geometry_column = 2;</code>
     */
    public java.lang.String getGeometryColumn() {
      java.lang.Object ref = geometryColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        geometryColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGeometryColumnBytes() {
      java.lang.Object ref = geometryColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        geometryColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder setGeometryColumn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      geometryColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder clearGeometryColumn() {
      
      geometryColumn_ = getDefaultInstance().getGeometryColumn();
      onChanged();
      return this;
    }
    /**
     * <code>string geometry_column = 2;</code>
     */
    public Builder setGeometryColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      geometryColumn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object targetColumn_ = "";
    /**
     * <code>string target_column = 3;</code>
     */
    public java.lang.String getTargetColumn() {
      java.lang.Object ref = targetColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_column = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetColumnBytes() {
      java.lang.Object ref = targetColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_column = 3;</code>
     */
    public Builder setTargetColumn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string target_column = 3;</code>
     */
    public Builder clearTargetColumn() {
      
      targetColumn_ = getDefaultInstance().getTargetColumn();
      onChanged();
      return this;
    }
    /**
     * <code>string target_column = 3;</code>
     */
    public Builder setTargetColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetColumn_ = value;
      onChanged();
      return this;
    }

    private double radius_ ;
    /**
     * <code>double radius = 4;</code>
     */
    public double getRadius() {
      return radius_;
    }
    /**
     * <code>double radius = 4;</code>
     */
    public Builder setRadius(double value) {
      
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double radius = 4;</code>
     */
    public Builder clearRadius() {
      
      radius_ = 0D;
      onChanged();
      return this;
    }

    private int wtype_ = 0;
    /**
     * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
     */
    public int getWtypeValue() {
      return wtype_;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
     */
    public Builder setWtypeValue(int value) {
      wtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
     */
    public marmot.proto.optor.LISAWeightProto getWtype() {
      marmot.proto.optor.LISAWeightProto result = marmot.proto.optor.LISAWeightProto.valueOf(wtype_);
      return result == null ? marmot.proto.optor.LISAWeightProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
     */
    public Builder setWtype(marmot.proto.optor.LISAWeightProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      wtype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.LISAWeightProto wtype = 5;</code>
     */
    public Builder clearWtype() {
      
      wtype_ = 0;
      onChanged();
      return this;
    }

    private double average_ ;
    /**
     * <code>double average = 6;</code>
     */
    public double getAverage() {
      return average_;
    }
    /**
     * <code>double average = 6;</code>
     */
    public Builder setAverage(double value) {
      
      average_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double average = 6;</code>
     */
    public Builder clearAverage() {
      
      average_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.CalcGlobalMoranIIntermediateProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.CalcGlobalMoranIIntermediateProto)
  private static final marmot.proto.optor.CalcGlobalMoranIIntermediateProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.CalcGlobalMoranIIntermediateProto();
  }

  public static marmot.proto.optor.CalcGlobalMoranIIntermediateProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalcGlobalMoranIIntermediateProto>
      PARSER = new com.google.protobuf.AbstractParser<CalcGlobalMoranIIntermediateProto>() {
    public CalcGlobalMoranIIntermediateProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalcGlobalMoranIIntermediateProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalcGlobalMoranIIntermediateProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalcGlobalMoranIIntermediateProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.CalcGlobalMoranIIntermediateProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

