// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface CombineByGroupProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.CombineByGroupProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_columns = 1;</code>
   */
  java.lang.String getKeyColumns();
  /**
   * <code>string key_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyColumnsBytes();

  /**
   * <code>string tag_columns = 2;</code>
   */
  java.lang.String getTagColumns();
  /**
   * <code>string tag_columns = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagColumnsBytes();

  /**
   * <code>string order_columns = 3;</code>
   */
  java.lang.String getOrderColumns();
  /**
   * <code>string order_columns = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrderColumnsBytes();

  /**
   * <code>.marmot.proto.SerializedProto reducer = 4;</code>
   */
  boolean hasReducer();
  /**
   * <code>.marmot.proto.SerializedProto reducer = 4;</code>
   */
  marmot.proto.SerializedProto getReducer();
  /**
   * <code>.marmot.proto.SerializedProto reducer = 4;</code>
   */
  marmot.proto.SerializedProtoOrBuilder getReducerOrBuilder();
}
