// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface CreateIndexedClusterPackProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.CreateIndexedClusterPackProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_dir = 1;</code>
   */
  java.lang.String getClusterDir();
  /**
   * <code>string cluster_dir = 1;</code>
   */
  com.google.protobuf.ByteString
      getClusterDirBytes();

  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  boolean hasGeometryColumnInfo();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  marmot.proto.GeometryColumnInfoProto getGeometryColumnInfo();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  marmot.proto.GeometryColumnInfoProtoOrBuilder getGeometryColumnInfoOrBuilder();

  /**
   * <code>int64 block_size = 3;</code>
   */
  long getBlockSize();
}
