// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * Protobuf type {@code marmot.proto.optor.CreateIndexedClusterPackProto}
 */
public  final class CreateIndexedClusterPackProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.CreateIndexedClusterPackProto)
    CreateIndexedClusterPackProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateIndexedClusterPackProto.newBuilder() to construct.
  private CreateIndexedClusterPackProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateIndexedClusterPackProto() {
    clusterDir_ = "";
    blockSize_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateIndexedClusterPackProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterDir_ = s;
            break;
          }
          case 18: {
            marmot.proto.GeometryColumnInfoProto.Builder subBuilder = null;
            if (geometryColumnInfo_ != null) {
              subBuilder = geometryColumnInfo_.toBuilder();
            }
            geometryColumnInfo_ = input.readMessage(marmot.proto.GeometryColumnInfoProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(geometryColumnInfo_);
              geometryColumnInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            blockSize_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.CreateIndexedClusterPackProto.class, marmot.proto.optor.CreateIndexedClusterPackProto.Builder.class);
  }

  public static final int CLUSTER_DIR_FIELD_NUMBER = 1;
  private volatile java.lang.Object clusterDir_;
  /**
   * <code>string cluster_dir = 1;</code>
   */
  public java.lang.String getClusterDir() {
    java.lang.Object ref = clusterDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterDir_ = s;
      return s;
    }
  }
  /**
   * <code>string cluster_dir = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClusterDirBytes() {
    java.lang.Object ref = clusterDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GEOMETRY_COLUMN_INFO_FIELD_NUMBER = 2;
  private marmot.proto.GeometryColumnInfoProto geometryColumnInfo_;
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  public boolean hasGeometryColumnInfo() {
    return geometryColumnInfo_ != null;
  }
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  public marmot.proto.GeometryColumnInfoProto getGeometryColumnInfo() {
    return geometryColumnInfo_ == null ? marmot.proto.GeometryColumnInfoProto.getDefaultInstance() : geometryColumnInfo_;
  }
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
   */
  public marmot.proto.GeometryColumnInfoProtoOrBuilder getGeometryColumnInfoOrBuilder() {
    return getGeometryColumnInfo();
  }

  public static final int BLOCK_SIZE_FIELD_NUMBER = 3;
  private long blockSize_;
  /**
   * <code>int64 block_size = 3;</code>
   */
  public long getBlockSize() {
    return blockSize_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clusterDir_);
    }
    if (geometryColumnInfo_ != null) {
      output.writeMessage(2, getGeometryColumnInfo());
    }
    if (blockSize_ != 0L) {
      output.writeInt64(3, blockSize_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clusterDir_);
    }
    if (geometryColumnInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGeometryColumnInfo());
    }
    if (blockSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, blockSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.CreateIndexedClusterPackProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.CreateIndexedClusterPackProto other = (marmot.proto.optor.CreateIndexedClusterPackProto) obj;

    boolean result = true;
    result = result && getClusterDir()
        .equals(other.getClusterDir());
    result = result && (hasGeometryColumnInfo() == other.hasGeometryColumnInfo());
    if (hasGeometryColumnInfo()) {
      result = result && getGeometryColumnInfo()
          .equals(other.getGeometryColumnInfo());
    }
    result = result && (getBlockSize()
        == other.getBlockSize());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTER_DIR_FIELD_NUMBER;
    hash = (53 * hash) + getClusterDir().hashCode();
    if (hasGeometryColumnInfo()) {
      hash = (37 * hash) + GEOMETRY_COLUMN_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getGeometryColumnInfo().hashCode();
    }
    hash = (37 * hash) + BLOCK_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.CreateIndexedClusterPackProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.CreateIndexedClusterPackProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marmot.proto.optor.CreateIndexedClusterPackProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.CreateIndexedClusterPackProto)
      marmot.proto.optor.CreateIndexedClusterPackProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.CreateIndexedClusterPackProto.class, marmot.proto.optor.CreateIndexedClusterPackProto.Builder.class);
    }

    // Construct using marmot.proto.optor.CreateIndexedClusterPackProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clusterDir_ = "";

      if (geometryColumnInfoBuilder_ == null) {
        geometryColumnInfo_ = null;
      } else {
        geometryColumnInfo_ = null;
        geometryColumnInfoBuilder_ = null;
      }
      blockSize_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor;
    }

    public marmot.proto.optor.CreateIndexedClusterPackProto getDefaultInstanceForType() {
      return marmot.proto.optor.CreateIndexedClusterPackProto.getDefaultInstance();
    }

    public marmot.proto.optor.CreateIndexedClusterPackProto build() {
      marmot.proto.optor.CreateIndexedClusterPackProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.CreateIndexedClusterPackProto buildPartial() {
      marmot.proto.optor.CreateIndexedClusterPackProto result = new marmot.proto.optor.CreateIndexedClusterPackProto(this);
      result.clusterDir_ = clusterDir_;
      if (geometryColumnInfoBuilder_ == null) {
        result.geometryColumnInfo_ = geometryColumnInfo_;
      } else {
        result.geometryColumnInfo_ = geometryColumnInfoBuilder_.build();
      }
      result.blockSize_ = blockSize_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.CreateIndexedClusterPackProto) {
        return mergeFrom((marmot.proto.optor.CreateIndexedClusterPackProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.CreateIndexedClusterPackProto other) {
      if (other == marmot.proto.optor.CreateIndexedClusterPackProto.getDefaultInstance()) return this;
      if (!other.getClusterDir().isEmpty()) {
        clusterDir_ = other.clusterDir_;
        onChanged();
      }
      if (other.hasGeometryColumnInfo()) {
        mergeGeometryColumnInfo(other.getGeometryColumnInfo());
      }
      if (other.getBlockSize() != 0L) {
        setBlockSize(other.getBlockSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.CreateIndexedClusterPackProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.CreateIndexedClusterPackProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clusterDir_ = "";
    /**
     * <code>string cluster_dir = 1;</code>
     */
    public java.lang.String getClusterDir() {
      java.lang.Object ref = clusterDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cluster_dir = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClusterDirBytes() {
      java.lang.Object ref = clusterDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cluster_dir = 1;</code>
     */
    public Builder setClusterDir(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cluster_dir = 1;</code>
     */
    public Builder clearClusterDir() {
      
      clusterDir_ = getDefaultInstance().getClusterDir();
      onChanged();
      return this;
    }
    /**
     * <code>string cluster_dir = 1;</code>
     */
    public Builder setClusterDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterDir_ = value;
      onChanged();
      return this;
    }

    private marmot.proto.GeometryColumnInfoProto geometryColumnInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.GeometryColumnInfoProto, marmot.proto.GeometryColumnInfoProto.Builder, marmot.proto.GeometryColumnInfoProtoOrBuilder> geometryColumnInfoBuilder_;
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public boolean hasGeometryColumnInfo() {
      return geometryColumnInfoBuilder_ != null || geometryColumnInfo_ != null;
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public marmot.proto.GeometryColumnInfoProto getGeometryColumnInfo() {
      if (geometryColumnInfoBuilder_ == null) {
        return geometryColumnInfo_ == null ? marmot.proto.GeometryColumnInfoProto.getDefaultInstance() : geometryColumnInfo_;
      } else {
        return geometryColumnInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public Builder setGeometryColumnInfo(marmot.proto.GeometryColumnInfoProto value) {
      if (geometryColumnInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        geometryColumnInfo_ = value;
        onChanged();
      } else {
        geometryColumnInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public Builder setGeometryColumnInfo(
        marmot.proto.GeometryColumnInfoProto.Builder builderForValue) {
      if (geometryColumnInfoBuilder_ == null) {
        geometryColumnInfo_ = builderForValue.build();
        onChanged();
      } else {
        geometryColumnInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public Builder mergeGeometryColumnInfo(marmot.proto.GeometryColumnInfoProto value) {
      if (geometryColumnInfoBuilder_ == null) {
        if (geometryColumnInfo_ != null) {
          geometryColumnInfo_ =
            marmot.proto.GeometryColumnInfoProto.newBuilder(geometryColumnInfo_).mergeFrom(value).buildPartial();
        } else {
          geometryColumnInfo_ = value;
        }
        onChanged();
      } else {
        geometryColumnInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public Builder clearGeometryColumnInfo() {
      if (geometryColumnInfoBuilder_ == null) {
        geometryColumnInfo_ = null;
        onChanged();
      } else {
        geometryColumnInfo_ = null;
        geometryColumnInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public marmot.proto.GeometryColumnInfoProto.Builder getGeometryColumnInfoBuilder() {
      
      onChanged();
      return getGeometryColumnInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    public marmot.proto.GeometryColumnInfoProtoOrBuilder getGeometryColumnInfoOrBuilder() {
      if (geometryColumnInfoBuilder_ != null) {
        return geometryColumnInfoBuilder_.getMessageOrBuilder();
      } else {
        return geometryColumnInfo_ == null ?
            marmot.proto.GeometryColumnInfoProto.getDefaultInstance() : geometryColumnInfo_;
      }
    }
    /**
     * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.GeometryColumnInfoProto, marmot.proto.GeometryColumnInfoProto.Builder, marmot.proto.GeometryColumnInfoProtoOrBuilder> 
        getGeometryColumnInfoFieldBuilder() {
      if (geometryColumnInfoBuilder_ == null) {
        geometryColumnInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.GeometryColumnInfoProto, marmot.proto.GeometryColumnInfoProto.Builder, marmot.proto.GeometryColumnInfoProtoOrBuilder>(
                getGeometryColumnInfo(),
                getParentForChildren(),
                isClean());
        geometryColumnInfo_ = null;
      }
      return geometryColumnInfoBuilder_;
    }

    private long blockSize_ ;
    /**
     * <code>int64 block_size = 3;</code>
     */
    public long getBlockSize() {
      return blockSize_;
    }
    /**
     * <code>int64 block_size = 3;</code>
     */
    public Builder setBlockSize(long value) {
      
      blockSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 block_size = 3;</code>
     */
    public Builder clearBlockSize() {
      
      blockSize_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.CreateIndexedClusterPackProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.CreateIndexedClusterPackProto)
  private static final marmot.proto.optor.CreateIndexedClusterPackProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.CreateIndexedClusterPackProto();
  }

  public static marmot.proto.optor.CreateIndexedClusterPackProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateIndexedClusterPackProto>
      PARSER = new com.google.protobuf.AbstractParser<CreateIndexedClusterPackProto>() {
    public CreateIndexedClusterPackProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateIndexedClusterPackProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateIndexedClusterPackProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateIndexedClusterPackProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.CreateIndexedClusterPackProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

