// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface FinalizeByGroupProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.FinalizeByGroupProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_columns = 1;</code>
   */
  java.lang.String getKeyColumns();
  /**
   * <code>string key_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyColumnsBytes();

  /**
   * <code>string tag_columns = 2;</code>
   */
  java.lang.String getTagColumns();
  /**
   * <code>string tag_columns = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagColumnsBytes();

  /**
   * <code>.marmot.proto.SerializedProto finalizer = 3;</code>
   */
  boolean hasFinalizer();
  /**
   * <code>.marmot.proto.SerializedProto finalizer = 3;</code>
   */
  marmot.proto.SerializedProto getFinalizer();
  /**
   * <code>.marmot.proto.SerializedProto finalizer = 3;</code>
   */
  marmot.proto.SerializedProtoOrBuilder getFinalizerOrBuilder();
}
