// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface IdentityRecordTransformProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.IdentityRecordTransformProto)
    com.google.protobuf.MessageOrBuilder {
}
