// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * Protobuf type {@code marmot.proto.optor.JoinPartitionsProto}
 */
public  final class JoinPartitionsProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.JoinPartitionsProto)
    JoinPartitionsProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinPartitionsProto.newBuilder() to construct.
  private JoinPartitionsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinPartitionsProto() {
    joinColumns_ = "";
    leftPrefix_ = "";
    rightPrefix_ = "";
    outputColumnExpr_ = "";
    joinType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JoinPartitionsProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            joinColumns_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            leftPrefix_ = s;
            break;
          }
          case 26: {
            marmot.proto.RecordSchemaProto.Builder subBuilder = null;
            if (leftRecordSchema_ != null) {
              subBuilder = leftRecordSchema_.toBuilder();
            }
            leftRecordSchema_ = input.readMessage(marmot.proto.RecordSchemaProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(leftRecordSchema_);
              leftRecordSchema_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            rightPrefix_ = s;
            break;
          }
          case 42: {
            marmot.proto.RecordSchemaProto.Builder subBuilder = null;
            if (rightRecordSchema_ != null) {
              subBuilder = rightRecordSchema_.toBuilder();
            }
            rightRecordSchema_ = input.readMessage(marmot.proto.RecordSchemaProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rightRecordSchema_);
              rightRecordSchema_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            outputColumnExpr_ = s;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            joinType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_JoinPartitionsProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.JoinPartitionsProto.class, marmot.proto.optor.JoinPartitionsProto.Builder.class);
  }

  public static final int JOIN_COLUMNS_FIELD_NUMBER = 1;
  private volatile java.lang.Object joinColumns_;
  /**
   * <code>string join_columns = 1;</code>
   */
  public java.lang.String getJoinColumns() {
    java.lang.Object ref = joinColumns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      joinColumns_ = s;
      return s;
    }
  }
  /**
   * <code>string join_columns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getJoinColumnsBytes() {
    java.lang.Object ref = joinColumns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      joinColumns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEFT_PREFIX_FIELD_NUMBER = 2;
  private volatile java.lang.Object leftPrefix_;
  /**
   * <code>string left_prefix = 2;</code>
   */
  public java.lang.String getLeftPrefix() {
    java.lang.Object ref = leftPrefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leftPrefix_ = s;
      return s;
    }
  }
  /**
   * <code>string left_prefix = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLeftPrefixBytes() {
    java.lang.Object ref = leftPrefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leftPrefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEFT_RECORD_SCHEMA_FIELD_NUMBER = 3;
  private marmot.proto.RecordSchemaProto leftRecordSchema_;
  /**
   * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
   */
  public boolean hasLeftRecordSchema() {
    return leftRecordSchema_ != null;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
   */
  public marmot.proto.RecordSchemaProto getLeftRecordSchema() {
    return leftRecordSchema_ == null ? marmot.proto.RecordSchemaProto.getDefaultInstance() : leftRecordSchema_;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
   */
  public marmot.proto.RecordSchemaProtoOrBuilder getLeftRecordSchemaOrBuilder() {
    return getLeftRecordSchema();
  }

  public static final int RIGHT_PREFIX_FIELD_NUMBER = 4;
  private volatile java.lang.Object rightPrefix_;
  /**
   * <code>string right_prefix = 4;</code>
   */
  public java.lang.String getRightPrefix() {
    java.lang.Object ref = rightPrefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rightPrefix_ = s;
      return s;
    }
  }
  /**
   * <code>string right_prefix = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRightPrefixBytes() {
    java.lang.Object ref = rightPrefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rightPrefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RIGHT_RECORD_SCHEMA_FIELD_NUMBER = 5;
  private marmot.proto.RecordSchemaProto rightRecordSchema_;
  /**
   * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
   */
  public boolean hasRightRecordSchema() {
    return rightRecordSchema_ != null;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
   */
  public marmot.proto.RecordSchemaProto getRightRecordSchema() {
    return rightRecordSchema_ == null ? marmot.proto.RecordSchemaProto.getDefaultInstance() : rightRecordSchema_;
  }
  /**
   * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
   */
  public marmot.proto.RecordSchemaProtoOrBuilder getRightRecordSchemaOrBuilder() {
    return getRightRecordSchema();
  }

  public static final int OUTPUT_COLUMN_EXPR_FIELD_NUMBER = 6;
  private volatile java.lang.Object outputColumnExpr_;
  /**
   * <code>string output_column_expr = 6;</code>
   */
  public java.lang.String getOutputColumnExpr() {
    java.lang.Object ref = outputColumnExpr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputColumnExpr_ = s;
      return s;
    }
  }
  /**
   * <code>string output_column_expr = 6;</code>
   */
  public com.google.protobuf.ByteString
      getOutputColumnExprBytes() {
    java.lang.Object ref = outputColumnExpr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputColumnExpr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOIN_TYPE_FIELD_NUMBER = 7;
  private int joinType_;
  /**
   * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
   */
  public int getJoinTypeValue() {
    return joinType_;
  }
  /**
   * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
   */
  public marmot.proto.optor.JoinTypeProto getJoinType() {
    marmot.proto.optor.JoinTypeProto result = marmot.proto.optor.JoinTypeProto.valueOf(joinType_);
    return result == null ? marmot.proto.optor.JoinTypeProto.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJoinColumnsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, joinColumns_);
    }
    if (!getLeftPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leftPrefix_);
    }
    if (leftRecordSchema_ != null) {
      output.writeMessage(3, getLeftRecordSchema());
    }
    if (!getRightPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rightPrefix_);
    }
    if (rightRecordSchema_ != null) {
      output.writeMessage(5, getRightRecordSchema());
    }
    if (!getOutputColumnExprBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, outputColumnExpr_);
    }
    if (joinType_ != marmot.proto.optor.JoinTypeProto.INNER_JOIN.getNumber()) {
      output.writeEnum(7, joinType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJoinColumnsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, joinColumns_);
    }
    if (!getLeftPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leftPrefix_);
    }
    if (leftRecordSchema_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLeftRecordSchema());
    }
    if (!getRightPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rightPrefix_);
    }
    if (rightRecordSchema_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRightRecordSchema());
    }
    if (!getOutputColumnExprBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, outputColumnExpr_);
    }
    if (joinType_ != marmot.proto.optor.JoinTypeProto.INNER_JOIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, joinType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.JoinPartitionsProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.JoinPartitionsProto other = (marmot.proto.optor.JoinPartitionsProto) obj;

    boolean result = true;
    result = result && getJoinColumns()
        .equals(other.getJoinColumns());
    result = result && getLeftPrefix()
        .equals(other.getLeftPrefix());
    result = result && (hasLeftRecordSchema() == other.hasLeftRecordSchema());
    if (hasLeftRecordSchema()) {
      result = result && getLeftRecordSchema()
          .equals(other.getLeftRecordSchema());
    }
    result = result && getRightPrefix()
        .equals(other.getRightPrefix());
    result = result && (hasRightRecordSchema() == other.hasRightRecordSchema());
    if (hasRightRecordSchema()) {
      result = result && getRightRecordSchema()
          .equals(other.getRightRecordSchema());
    }
    result = result && getOutputColumnExpr()
        .equals(other.getOutputColumnExpr());
    result = result && joinType_ == other.joinType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOIN_COLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + getJoinColumns().hashCode();
    hash = (37 * hash) + LEFT_PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getLeftPrefix().hashCode();
    if (hasLeftRecordSchema()) {
      hash = (37 * hash) + LEFT_RECORD_SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getLeftRecordSchema().hashCode();
    }
    hash = (37 * hash) + RIGHT_PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getRightPrefix().hashCode();
    if (hasRightRecordSchema()) {
      hash = (37 * hash) + RIGHT_RECORD_SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getRightRecordSchema().hashCode();
    }
    hash = (37 * hash) + OUTPUT_COLUMN_EXPR_FIELD_NUMBER;
    hash = (53 * hash) + getOutputColumnExpr().hashCode();
    hash = (37 * hash) + JOIN_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + joinType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.JoinPartitionsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.JoinPartitionsProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marmot.proto.optor.JoinPartitionsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.JoinPartitionsProto)
      marmot.proto.optor.JoinPartitionsProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_JoinPartitionsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.JoinPartitionsProto.class, marmot.proto.optor.JoinPartitionsProto.Builder.class);
    }

    // Construct using marmot.proto.optor.JoinPartitionsProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      joinColumns_ = "";

      leftPrefix_ = "";

      if (leftRecordSchemaBuilder_ == null) {
        leftRecordSchema_ = null;
      } else {
        leftRecordSchema_ = null;
        leftRecordSchemaBuilder_ = null;
      }
      rightPrefix_ = "";

      if (rightRecordSchemaBuilder_ == null) {
        rightRecordSchema_ = null;
      } else {
        rightRecordSchema_ = null;
        rightRecordSchemaBuilder_ = null;
      }
      outputColumnExpr_ = "";

      joinType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor;
    }

    public marmot.proto.optor.JoinPartitionsProto getDefaultInstanceForType() {
      return marmot.proto.optor.JoinPartitionsProto.getDefaultInstance();
    }

    public marmot.proto.optor.JoinPartitionsProto build() {
      marmot.proto.optor.JoinPartitionsProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.JoinPartitionsProto buildPartial() {
      marmot.proto.optor.JoinPartitionsProto result = new marmot.proto.optor.JoinPartitionsProto(this);
      result.joinColumns_ = joinColumns_;
      result.leftPrefix_ = leftPrefix_;
      if (leftRecordSchemaBuilder_ == null) {
        result.leftRecordSchema_ = leftRecordSchema_;
      } else {
        result.leftRecordSchema_ = leftRecordSchemaBuilder_.build();
      }
      result.rightPrefix_ = rightPrefix_;
      if (rightRecordSchemaBuilder_ == null) {
        result.rightRecordSchema_ = rightRecordSchema_;
      } else {
        result.rightRecordSchema_ = rightRecordSchemaBuilder_.build();
      }
      result.outputColumnExpr_ = outputColumnExpr_;
      result.joinType_ = joinType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.JoinPartitionsProto) {
        return mergeFrom((marmot.proto.optor.JoinPartitionsProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.JoinPartitionsProto other) {
      if (other == marmot.proto.optor.JoinPartitionsProto.getDefaultInstance()) return this;
      if (!other.getJoinColumns().isEmpty()) {
        joinColumns_ = other.joinColumns_;
        onChanged();
      }
      if (!other.getLeftPrefix().isEmpty()) {
        leftPrefix_ = other.leftPrefix_;
        onChanged();
      }
      if (other.hasLeftRecordSchema()) {
        mergeLeftRecordSchema(other.getLeftRecordSchema());
      }
      if (!other.getRightPrefix().isEmpty()) {
        rightPrefix_ = other.rightPrefix_;
        onChanged();
      }
      if (other.hasRightRecordSchema()) {
        mergeRightRecordSchema(other.getRightRecordSchema());
      }
      if (!other.getOutputColumnExpr().isEmpty()) {
        outputColumnExpr_ = other.outputColumnExpr_;
        onChanged();
      }
      if (other.joinType_ != 0) {
        setJoinTypeValue(other.getJoinTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.JoinPartitionsProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.JoinPartitionsProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object joinColumns_ = "";
    /**
     * <code>string join_columns = 1;</code>
     */
    public java.lang.String getJoinColumns() {
      java.lang.Object ref = joinColumns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        joinColumns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJoinColumnsBytes() {
      java.lang.Object ref = joinColumns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        joinColumns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder setJoinColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      joinColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder clearJoinColumns() {
      
      joinColumns_ = getDefaultInstance().getJoinColumns();
      onChanged();
      return this;
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder setJoinColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      joinColumns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object leftPrefix_ = "";
    /**
     * <code>string left_prefix = 2;</code>
     */
    public java.lang.String getLeftPrefix() {
      java.lang.Object ref = leftPrefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leftPrefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string left_prefix = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeftPrefixBytes() {
      java.lang.Object ref = leftPrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leftPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string left_prefix = 2;</code>
     */
    public Builder setLeftPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leftPrefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string left_prefix = 2;</code>
     */
    public Builder clearLeftPrefix() {
      
      leftPrefix_ = getDefaultInstance().getLeftPrefix();
      onChanged();
      return this;
    }
    /**
     * <code>string left_prefix = 2;</code>
     */
    public Builder setLeftPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leftPrefix_ = value;
      onChanged();
      return this;
    }

    private marmot.proto.RecordSchemaProto leftRecordSchema_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> leftRecordSchemaBuilder_;
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public boolean hasLeftRecordSchema() {
      return leftRecordSchemaBuilder_ != null || leftRecordSchema_ != null;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public marmot.proto.RecordSchemaProto getLeftRecordSchema() {
      if (leftRecordSchemaBuilder_ == null) {
        return leftRecordSchema_ == null ? marmot.proto.RecordSchemaProto.getDefaultInstance() : leftRecordSchema_;
      } else {
        return leftRecordSchemaBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public Builder setLeftRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (leftRecordSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leftRecordSchema_ = value;
        onChanged();
      } else {
        leftRecordSchemaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public Builder setLeftRecordSchema(
        marmot.proto.RecordSchemaProto.Builder builderForValue) {
      if (leftRecordSchemaBuilder_ == null) {
        leftRecordSchema_ = builderForValue.build();
        onChanged();
      } else {
        leftRecordSchemaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public Builder mergeLeftRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (leftRecordSchemaBuilder_ == null) {
        if (leftRecordSchema_ != null) {
          leftRecordSchema_ =
            marmot.proto.RecordSchemaProto.newBuilder(leftRecordSchema_).mergeFrom(value).buildPartial();
        } else {
          leftRecordSchema_ = value;
        }
        onChanged();
      } else {
        leftRecordSchemaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public Builder clearLeftRecordSchema() {
      if (leftRecordSchemaBuilder_ == null) {
        leftRecordSchema_ = null;
        onChanged();
      } else {
        leftRecordSchema_ = null;
        leftRecordSchemaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public marmot.proto.RecordSchemaProto.Builder getLeftRecordSchemaBuilder() {
      
      onChanged();
      return getLeftRecordSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    public marmot.proto.RecordSchemaProtoOrBuilder getLeftRecordSchemaOrBuilder() {
      if (leftRecordSchemaBuilder_ != null) {
        return leftRecordSchemaBuilder_.getMessageOrBuilder();
      } else {
        return leftRecordSchema_ == null ?
            marmot.proto.RecordSchemaProto.getDefaultInstance() : leftRecordSchema_;
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto left_record_schema = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> 
        getLeftRecordSchemaFieldBuilder() {
      if (leftRecordSchemaBuilder_ == null) {
        leftRecordSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder>(
                getLeftRecordSchema(),
                getParentForChildren(),
                isClean());
        leftRecordSchema_ = null;
      }
      return leftRecordSchemaBuilder_;
    }

    private java.lang.Object rightPrefix_ = "";
    /**
     * <code>string right_prefix = 4;</code>
     */
    public java.lang.String getRightPrefix() {
      java.lang.Object ref = rightPrefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rightPrefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string right_prefix = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRightPrefixBytes() {
      java.lang.Object ref = rightPrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rightPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string right_prefix = 4;</code>
     */
    public Builder setRightPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rightPrefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string right_prefix = 4;</code>
     */
    public Builder clearRightPrefix() {
      
      rightPrefix_ = getDefaultInstance().getRightPrefix();
      onChanged();
      return this;
    }
    /**
     * <code>string right_prefix = 4;</code>
     */
    public Builder setRightPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rightPrefix_ = value;
      onChanged();
      return this;
    }

    private marmot.proto.RecordSchemaProto rightRecordSchema_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> rightRecordSchemaBuilder_;
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public boolean hasRightRecordSchema() {
      return rightRecordSchemaBuilder_ != null || rightRecordSchema_ != null;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public marmot.proto.RecordSchemaProto getRightRecordSchema() {
      if (rightRecordSchemaBuilder_ == null) {
        return rightRecordSchema_ == null ? marmot.proto.RecordSchemaProto.getDefaultInstance() : rightRecordSchema_;
      } else {
        return rightRecordSchemaBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public Builder setRightRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (rightRecordSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rightRecordSchema_ = value;
        onChanged();
      } else {
        rightRecordSchemaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public Builder setRightRecordSchema(
        marmot.proto.RecordSchemaProto.Builder builderForValue) {
      if (rightRecordSchemaBuilder_ == null) {
        rightRecordSchema_ = builderForValue.build();
        onChanged();
      } else {
        rightRecordSchemaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public Builder mergeRightRecordSchema(marmot.proto.RecordSchemaProto value) {
      if (rightRecordSchemaBuilder_ == null) {
        if (rightRecordSchema_ != null) {
          rightRecordSchema_ =
            marmot.proto.RecordSchemaProto.newBuilder(rightRecordSchema_).mergeFrom(value).buildPartial();
        } else {
          rightRecordSchema_ = value;
        }
        onChanged();
      } else {
        rightRecordSchemaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public Builder clearRightRecordSchema() {
      if (rightRecordSchemaBuilder_ == null) {
        rightRecordSchema_ = null;
        onChanged();
      } else {
        rightRecordSchema_ = null;
        rightRecordSchemaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public marmot.proto.RecordSchemaProto.Builder getRightRecordSchemaBuilder() {
      
      onChanged();
      return getRightRecordSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    public marmot.proto.RecordSchemaProtoOrBuilder getRightRecordSchemaOrBuilder() {
      if (rightRecordSchemaBuilder_ != null) {
        return rightRecordSchemaBuilder_.getMessageOrBuilder();
      } else {
        return rightRecordSchema_ == null ?
            marmot.proto.RecordSchemaProto.getDefaultInstance() : rightRecordSchema_;
      }
    }
    /**
     * <code>.marmot.proto.RecordSchemaProto right_record_schema = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder> 
        getRightRecordSchemaFieldBuilder() {
      if (rightRecordSchemaBuilder_ == null) {
        rightRecordSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.RecordSchemaProto, marmot.proto.RecordSchemaProto.Builder, marmot.proto.RecordSchemaProtoOrBuilder>(
                getRightRecordSchema(),
                getParentForChildren(),
                isClean());
        rightRecordSchema_ = null;
      }
      return rightRecordSchemaBuilder_;
    }

    private java.lang.Object outputColumnExpr_ = "";
    /**
     * <code>string output_column_expr = 6;</code>
     */
    public java.lang.String getOutputColumnExpr() {
      java.lang.Object ref = outputColumnExpr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputColumnExpr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string output_column_expr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOutputColumnExprBytes() {
      java.lang.Object ref = outputColumnExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputColumnExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string output_column_expr = 6;</code>
     */
    public Builder setOutputColumnExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputColumnExpr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string output_column_expr = 6;</code>
     */
    public Builder clearOutputColumnExpr() {
      
      outputColumnExpr_ = getDefaultInstance().getOutputColumnExpr();
      onChanged();
      return this;
    }
    /**
     * <code>string output_column_expr = 6;</code>
     */
    public Builder setOutputColumnExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outputColumnExpr_ = value;
      onChanged();
      return this;
    }

    private int joinType_ = 0;
    /**
     * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
     */
    public int getJoinTypeValue() {
      return joinType_;
    }
    /**
     * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
     */
    public Builder setJoinTypeValue(int value) {
      joinType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
     */
    public marmot.proto.optor.JoinTypeProto getJoinType() {
      marmot.proto.optor.JoinTypeProto result = marmot.proto.optor.JoinTypeProto.valueOf(joinType_);
      return result == null ? marmot.proto.optor.JoinTypeProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
     */
    public Builder setJoinType(marmot.proto.optor.JoinTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      joinType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinTypeProto join_type = 7;</code>
     */
    public Builder clearJoinType() {
      
      joinType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.JoinPartitionsProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.JoinPartitionsProto)
  private static final marmot.proto.optor.JoinPartitionsProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.JoinPartitionsProto();
  }

  public static marmot.proto.optor.JoinPartitionsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinPartitionsProto>
      PARSER = new com.google.protobuf.AbstractParser<JoinPartitionsProto>() {
    public JoinPartitionsProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinPartitionsProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JoinPartitionsProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinPartitionsProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.JoinPartitionsProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

