// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface MapOutputWriterProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.MapOutputWriterProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string map_output_key_cols = 1;</code>
   */
  java.lang.String getMapOutputKeyCols();
  /**
   * <code>string map_output_key_cols = 1;</code>
   */
  com.google.protobuf.ByteString
      getMapOutputKeyColsBytes();

  public marmot.proto.optor.MapOutputWriterProto.OptionalMapOutputKeyColsCase getOptionalMapOutputKeyColsCase();
}
