// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface MapReduceEquiJoinProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.MapReduceEquiJoinProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string join_columns = 1;</code>
   */
  java.lang.String getJoinColumns();
  /**
   * <code>string join_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getJoinColumnsBytes();

  /**
   * <code>string param_dataset = 2;</code>
   */
  java.lang.String getParamDataset();
  /**
   * <code>string param_dataset = 2;</code>
   */
  com.google.protobuf.ByteString
      getParamDatasetBytes();

  /**
   * <code>string param_columns = 3;</code>
   */
  java.lang.String getParamColumns();
  /**
   * <code>string param_columns = 3;</code>
   */
  com.google.protobuf.ByteString
      getParamColumnsBytes();

  /**
   * <code>string output_column_expr = 4;</code>
   */
  java.lang.String getOutputColumnExpr();
  /**
   * <code>string output_column_expr = 4;</code>
   */
  com.google.protobuf.ByteString
      getOutputColumnExprBytes();

  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  boolean hasJoinOptions();
  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  marmot.proto.optor.JoinOptionsProto getJoinOptions();
  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  marmot.proto.optor.JoinOptionsProtoOrBuilder getJoinOptionsOrBuilder();
}
