// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * <pre>
 * EquiJoin 관련
 * </pre>
 *
 * Protobuf type {@code marmot.proto.optor.MapReduceEquiJoinProto}
 */
public  final class MapReduceEquiJoinProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.MapReduceEquiJoinProto)
    MapReduceEquiJoinProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MapReduceEquiJoinProto.newBuilder() to construct.
  private MapReduceEquiJoinProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MapReduceEquiJoinProto() {
    joinColumns_ = "";
    paramDataset_ = "";
    paramColumns_ = "";
    outputColumnExpr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MapReduceEquiJoinProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            joinColumns_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            paramDataset_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            paramColumns_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            outputColumnExpr_ = s;
            break;
          }
          case 42: {
            marmot.proto.optor.JoinOptionsProto.Builder subBuilder = null;
            if (joinOptions_ != null) {
              subBuilder = joinOptions_.toBuilder();
            }
            joinOptions_ = input.readMessage(marmot.proto.optor.JoinOptionsProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(joinOptions_);
              joinOptions_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_MapReduceEquiJoinProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.MapReduceEquiJoinProto.class, marmot.proto.optor.MapReduceEquiJoinProto.Builder.class);
  }

  public static final int JOIN_COLUMNS_FIELD_NUMBER = 1;
  private volatile java.lang.Object joinColumns_;
  /**
   * <code>string join_columns = 1;</code>
   */
  public java.lang.String getJoinColumns() {
    java.lang.Object ref = joinColumns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      joinColumns_ = s;
      return s;
    }
  }
  /**
   * <code>string join_columns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getJoinColumnsBytes() {
    java.lang.Object ref = joinColumns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      joinColumns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM_DATASET_FIELD_NUMBER = 2;
  private volatile java.lang.Object paramDataset_;
  /**
   * <code>string param_dataset = 2;</code>
   */
  public java.lang.String getParamDataset() {
    java.lang.Object ref = paramDataset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paramDataset_ = s;
      return s;
    }
  }
  /**
   * <code>string param_dataset = 2;</code>
   */
  public com.google.protobuf.ByteString
      getParamDatasetBytes() {
    java.lang.Object ref = paramDataset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paramDataset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM_COLUMNS_FIELD_NUMBER = 3;
  private volatile java.lang.Object paramColumns_;
  /**
   * <code>string param_columns = 3;</code>
   */
  public java.lang.String getParamColumns() {
    java.lang.Object ref = paramColumns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paramColumns_ = s;
      return s;
    }
  }
  /**
   * <code>string param_columns = 3;</code>
   */
  public com.google.protobuf.ByteString
      getParamColumnsBytes() {
    java.lang.Object ref = paramColumns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paramColumns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUT_COLUMN_EXPR_FIELD_NUMBER = 4;
  private volatile java.lang.Object outputColumnExpr_;
  /**
   * <code>string output_column_expr = 4;</code>
   */
  public java.lang.String getOutputColumnExpr() {
    java.lang.Object ref = outputColumnExpr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputColumnExpr_ = s;
      return s;
    }
  }
  /**
   * <code>string output_column_expr = 4;</code>
   */
  public com.google.protobuf.ByteString
      getOutputColumnExprBytes() {
    java.lang.Object ref = outputColumnExpr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputColumnExpr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOIN_OPTIONS_FIELD_NUMBER = 5;
  private marmot.proto.optor.JoinOptionsProto joinOptions_;
  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  public boolean hasJoinOptions() {
    return joinOptions_ != null;
  }
  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  public marmot.proto.optor.JoinOptionsProto getJoinOptions() {
    return joinOptions_ == null ? marmot.proto.optor.JoinOptionsProto.getDefaultInstance() : joinOptions_;
  }
  /**
   * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
   */
  public marmot.proto.optor.JoinOptionsProtoOrBuilder getJoinOptionsOrBuilder() {
    return getJoinOptions();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJoinColumnsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, joinColumns_);
    }
    if (!getParamDatasetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, paramDataset_);
    }
    if (!getParamColumnsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paramColumns_);
    }
    if (!getOutputColumnExprBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, outputColumnExpr_);
    }
    if (joinOptions_ != null) {
      output.writeMessage(5, getJoinOptions());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJoinColumnsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, joinColumns_);
    }
    if (!getParamDatasetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, paramDataset_);
    }
    if (!getParamColumnsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, paramColumns_);
    }
    if (!getOutputColumnExprBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, outputColumnExpr_);
    }
    if (joinOptions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getJoinOptions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.MapReduceEquiJoinProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.MapReduceEquiJoinProto other = (marmot.proto.optor.MapReduceEquiJoinProto) obj;

    boolean result = true;
    result = result && getJoinColumns()
        .equals(other.getJoinColumns());
    result = result && getParamDataset()
        .equals(other.getParamDataset());
    result = result && getParamColumns()
        .equals(other.getParamColumns());
    result = result && getOutputColumnExpr()
        .equals(other.getOutputColumnExpr());
    result = result && (hasJoinOptions() == other.hasJoinOptions());
    if (hasJoinOptions()) {
      result = result && getJoinOptions()
          .equals(other.getJoinOptions());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOIN_COLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + getJoinColumns().hashCode();
    hash = (37 * hash) + PARAM_DATASET_FIELD_NUMBER;
    hash = (53 * hash) + getParamDataset().hashCode();
    hash = (37 * hash) + PARAM_COLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + getParamColumns().hashCode();
    hash = (37 * hash) + OUTPUT_COLUMN_EXPR_FIELD_NUMBER;
    hash = (53 * hash) + getOutputColumnExpr().hashCode();
    if (hasJoinOptions()) {
      hash = (37 * hash) + JOIN_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getJoinOptions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.MapReduceEquiJoinProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.MapReduceEquiJoinProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * EquiJoin 관련
   * </pre>
   *
   * Protobuf type {@code marmot.proto.optor.MapReduceEquiJoinProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.MapReduceEquiJoinProto)
      marmot.proto.optor.MapReduceEquiJoinProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_MapReduceEquiJoinProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.MapReduceEquiJoinProto.class, marmot.proto.optor.MapReduceEquiJoinProto.Builder.class);
    }

    // Construct using marmot.proto.optor.MapReduceEquiJoinProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      joinColumns_ = "";

      paramDataset_ = "";

      paramColumns_ = "";

      outputColumnExpr_ = "";

      if (joinOptionsBuilder_ == null) {
        joinOptions_ = null;
      } else {
        joinOptions_ = null;
        joinOptionsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor;
    }

    public marmot.proto.optor.MapReduceEquiJoinProto getDefaultInstanceForType() {
      return marmot.proto.optor.MapReduceEquiJoinProto.getDefaultInstance();
    }

    public marmot.proto.optor.MapReduceEquiJoinProto build() {
      marmot.proto.optor.MapReduceEquiJoinProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.MapReduceEquiJoinProto buildPartial() {
      marmot.proto.optor.MapReduceEquiJoinProto result = new marmot.proto.optor.MapReduceEquiJoinProto(this);
      result.joinColumns_ = joinColumns_;
      result.paramDataset_ = paramDataset_;
      result.paramColumns_ = paramColumns_;
      result.outputColumnExpr_ = outputColumnExpr_;
      if (joinOptionsBuilder_ == null) {
        result.joinOptions_ = joinOptions_;
      } else {
        result.joinOptions_ = joinOptionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.MapReduceEquiJoinProto) {
        return mergeFrom((marmot.proto.optor.MapReduceEquiJoinProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.MapReduceEquiJoinProto other) {
      if (other == marmot.proto.optor.MapReduceEquiJoinProto.getDefaultInstance()) return this;
      if (!other.getJoinColumns().isEmpty()) {
        joinColumns_ = other.joinColumns_;
        onChanged();
      }
      if (!other.getParamDataset().isEmpty()) {
        paramDataset_ = other.paramDataset_;
        onChanged();
      }
      if (!other.getParamColumns().isEmpty()) {
        paramColumns_ = other.paramColumns_;
        onChanged();
      }
      if (!other.getOutputColumnExpr().isEmpty()) {
        outputColumnExpr_ = other.outputColumnExpr_;
        onChanged();
      }
      if (other.hasJoinOptions()) {
        mergeJoinOptions(other.getJoinOptions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.MapReduceEquiJoinProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.MapReduceEquiJoinProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object joinColumns_ = "";
    /**
     * <code>string join_columns = 1;</code>
     */
    public java.lang.String getJoinColumns() {
      java.lang.Object ref = joinColumns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        joinColumns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJoinColumnsBytes() {
      java.lang.Object ref = joinColumns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        joinColumns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder setJoinColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      joinColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder clearJoinColumns() {
      
      joinColumns_ = getDefaultInstance().getJoinColumns();
      onChanged();
      return this;
    }
    /**
     * <code>string join_columns = 1;</code>
     */
    public Builder setJoinColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      joinColumns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object paramDataset_ = "";
    /**
     * <code>string param_dataset = 2;</code>
     */
    public java.lang.String getParamDataset() {
      java.lang.Object ref = paramDataset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paramDataset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string param_dataset = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParamDatasetBytes() {
      java.lang.Object ref = paramDataset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paramDataset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string param_dataset = 2;</code>
     */
    public Builder setParamDataset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paramDataset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string param_dataset = 2;</code>
     */
    public Builder clearParamDataset() {
      
      paramDataset_ = getDefaultInstance().getParamDataset();
      onChanged();
      return this;
    }
    /**
     * <code>string param_dataset = 2;</code>
     */
    public Builder setParamDatasetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paramDataset_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object paramColumns_ = "";
    /**
     * <code>string param_columns = 3;</code>
     */
    public java.lang.String getParamColumns() {
      java.lang.Object ref = paramColumns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paramColumns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string param_columns = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParamColumnsBytes() {
      java.lang.Object ref = paramColumns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paramColumns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string param_columns = 3;</code>
     */
    public Builder setParamColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paramColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string param_columns = 3;</code>
     */
    public Builder clearParamColumns() {
      
      paramColumns_ = getDefaultInstance().getParamColumns();
      onChanged();
      return this;
    }
    /**
     * <code>string param_columns = 3;</code>
     */
    public Builder setParamColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paramColumns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object outputColumnExpr_ = "";
    /**
     * <code>string output_column_expr = 4;</code>
     */
    public java.lang.String getOutputColumnExpr() {
      java.lang.Object ref = outputColumnExpr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputColumnExpr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string output_column_expr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutputColumnExprBytes() {
      java.lang.Object ref = outputColumnExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputColumnExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string output_column_expr = 4;</code>
     */
    public Builder setOutputColumnExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputColumnExpr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string output_column_expr = 4;</code>
     */
    public Builder clearOutputColumnExpr() {
      
      outputColumnExpr_ = getDefaultInstance().getOutputColumnExpr();
      onChanged();
      return this;
    }
    /**
     * <code>string output_column_expr = 4;</code>
     */
    public Builder setOutputColumnExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outputColumnExpr_ = value;
      onChanged();
      return this;
    }

    private marmot.proto.optor.JoinOptionsProto joinOptions_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.optor.JoinOptionsProto, marmot.proto.optor.JoinOptionsProto.Builder, marmot.proto.optor.JoinOptionsProtoOrBuilder> joinOptionsBuilder_;
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public boolean hasJoinOptions() {
      return joinOptionsBuilder_ != null || joinOptions_ != null;
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public marmot.proto.optor.JoinOptionsProto getJoinOptions() {
      if (joinOptionsBuilder_ == null) {
        return joinOptions_ == null ? marmot.proto.optor.JoinOptionsProto.getDefaultInstance() : joinOptions_;
      } else {
        return joinOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public Builder setJoinOptions(marmot.proto.optor.JoinOptionsProto value) {
      if (joinOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        joinOptions_ = value;
        onChanged();
      } else {
        joinOptionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public Builder setJoinOptions(
        marmot.proto.optor.JoinOptionsProto.Builder builderForValue) {
      if (joinOptionsBuilder_ == null) {
        joinOptions_ = builderForValue.build();
        onChanged();
      } else {
        joinOptionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public Builder mergeJoinOptions(marmot.proto.optor.JoinOptionsProto value) {
      if (joinOptionsBuilder_ == null) {
        if (joinOptions_ != null) {
          joinOptions_ =
            marmot.proto.optor.JoinOptionsProto.newBuilder(joinOptions_).mergeFrom(value).buildPartial();
        } else {
          joinOptions_ = value;
        }
        onChanged();
      } else {
        joinOptionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public Builder clearJoinOptions() {
      if (joinOptionsBuilder_ == null) {
        joinOptions_ = null;
        onChanged();
      } else {
        joinOptions_ = null;
        joinOptionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public marmot.proto.optor.JoinOptionsProto.Builder getJoinOptionsBuilder() {
      
      onChanged();
      return getJoinOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    public marmot.proto.optor.JoinOptionsProtoOrBuilder getJoinOptionsOrBuilder() {
      if (joinOptionsBuilder_ != null) {
        return joinOptionsBuilder_.getMessageOrBuilder();
      } else {
        return joinOptions_ == null ?
            marmot.proto.optor.JoinOptionsProto.getDefaultInstance() : joinOptions_;
      }
    }
    /**
     * <code>.marmot.proto.optor.JoinOptionsProto join_options = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.optor.JoinOptionsProto, marmot.proto.optor.JoinOptionsProto.Builder, marmot.proto.optor.JoinOptionsProtoOrBuilder> 
        getJoinOptionsFieldBuilder() {
      if (joinOptionsBuilder_ == null) {
        joinOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.optor.JoinOptionsProto, marmot.proto.optor.JoinOptionsProto.Builder, marmot.proto.optor.JoinOptionsProtoOrBuilder>(
                getJoinOptions(),
                getParentForChildren(),
                isClean());
        joinOptions_ = null;
      }
      return joinOptionsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.MapReduceEquiJoinProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.MapReduceEquiJoinProto)
  private static final marmot.proto.optor.MapReduceEquiJoinProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.MapReduceEquiJoinProto();
  }

  public static marmot.proto.optor.MapReduceEquiJoinProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MapReduceEquiJoinProto>
      PARSER = new com.google.protobuf.AbstractParser<MapReduceEquiJoinProto>() {
    public MapReduceEquiJoinProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MapReduceEquiJoinProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MapReduceEquiJoinProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MapReduceEquiJoinProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.MapReduceEquiJoinProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

