// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public final class MarmotOptorInternal {
  private MarmotOptorInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_BuildThumbnailProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_BuildThumbnailProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_StoreDataSetPartitionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_StoreDataSetPartitionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_UpdateDataSetInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_UpdateDataSetInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_MapReduceEquiJoinProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_TagJoinKeyColumnsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_TagJoinKeyColumnsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_JoinPartitionsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_LeftOuterJoinAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_LeftOuterJoinAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_SemiJoinAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_SemiJoinAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_VARIntermediateProducerProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_VARIntermediateProducerProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_VARIntermediateCombinerProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_VARIntermediateCombinerProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_VARIntermediateFinalizerProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_VARIntermediateFinalizerProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_AggregateIntermAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_AggregateIntermAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_ProduceByGroupProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_ProduceByGroupProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_CombineByGroupProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_CombineByGroupProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_FinalizeByGroupProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_FinalizeByGroupProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_AggregateIntermByGroupAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_AggregateIntermByGroupAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_TakeNByGroupAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_TakeNByGroupAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_ReduceIntermByGroupAtMapSideProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_ReduceIntermByGroupAtMapSideProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_IdentityRecordTransformProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_IdentityRecordTransformProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_TakeCombinerProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_TakeCombinerProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_MapOutputWriterProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_MapOutputWriterProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_IntermediateTerminalProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_IntermediateTerminalProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_AssignClusterIdProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_AssignClusterIdProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_KMeansIterationProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_KMeansIterationProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_LISAParametersProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_LISAParametersProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_CalcGetisOrdGiProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_CalcGetisOrdGiProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_CalcLocalMoransIProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_MBRTaggedOpaqueTransformProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_MBRTaggedOpaqueTransformProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_SplitQuadSpaceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_SplitQuadSpaceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033marmot.optor.internal.proto\022\022marmot.pr" +
      "oto.optor\032\014marmot.proto\032\025marmot.internal" +
      ".proto\032\022marmot.optor.proto\032\024marmot.servi" +
      "ce.proto\"@\n\023BuildThumbnailProto\022\023\n\013geom_" +
      "column\030\001 \001(\t\022\024\n\014sample_ratio\030\002 \001(\001\"k\n\032St" +
      "oreDataSetPartitionProto\022\014\n\004path\030\001 \001(\t\022?" +
      "\n\007options\030\002 \001(\0132..marmot.proto.service.S" +
      "toreDataSetOptionsProto\"&\n\026UpdateDataSet" +
      "InfoProto\022\014\n\004name\030\001 \001(\t\"\264\001\n\026MapReduceEqu" +
      "iJoinProto\022\024\n\014join_columns\030\001 \001(\t\022\025\n\rpara" +
      "m_dataset\030\002 \001(\t\022\025\n\rparam_columns\030\003 \001(\t\022\032" +
      "\n\022output_column_expr\030\004 \001(\t\022:\n\014join_optio" +
      "ns\030\005 \001(\0132$.marmot.proto.optor.JoinOption" +
      "sProto\"\\\n\026TagJoinKeyColumnsProto\022\024\n\014join" +
      "_columns\030\001 \001(\t\022\025\n\rparam_dataset\030\002 \001(\t\022\025\n" +
      "\rparam_columns\030\003 \001(\t\"\243\002\n\023JoinPartitionsP" +
      "roto\022\024\n\014join_columns\030\001 \001(\t\022\023\n\013left_prefi" +
      "x\030\002 \001(\t\022;\n\022left_record_schema\030\003 \001(\0132\037.ma" +
      "rmot.proto.RecordSchemaProto\022\024\n\014right_pr" +
      "efix\030\004 \001(\t\022<\n\023right_record_schema\030\005 \001(\0132" +
      "\037.marmot.proto.RecordSchemaProto\022\032\n\022outp" +
      "ut_column_expr\030\006 \001(\t\0224\n\tjoin_type\030\007 \001(\0162" +
      "!.marmot.proto.optor.JoinTypeProto\"\210\001\n\033L" +
      "eftOuterJoinAtMapSideProto\022\032\n\022input_join" +
      "_columns\030\001 \001(\t\022\025\n\rparam_dataset\030\002 \001(\t\022\032\n" +
      "\022param_join_columns\030\003 \001(\t\022\032\n\022output_colu" +
      "mn_expr\030\004 \001(\t\"g\n\026SemiJoinAtMapSideProto\022" +
      "\032\n\022input_join_columns\030\001 \001(\t\022\025\n\rparam_dat" +
      "aset\030\002 \001(\t\022\032\n\022param_join_columns\030\003 \001(\t\"3" +
      "\n\034VARIntermediateProducerProto\022\023\n\013aggreg" +
      "ators\030\001 \003(\t\"3\n\034VARIntermediateCombinerPr" +
      "oto\022\023\n\013aggregators\030\001 \003(\t\"4\n\035VARIntermedi" +
      "ateFinalizerProto\022\023\n\013aggregators\030\001 \003(\t\"O" +
      "\n\035AggregateIntermAtMapSideProto\022.\n\007reduc" +
      "er\030\001 \001(\0132\035.marmot.proto.SerializedProto\"" +
      "p\n\023ProduceByGroupProto\022\023\n\013key_columns\030\001 " +
      "\001(\t\022\023\n\013tag_columns\030\002 \001(\t\022/\n\010producer\030\003 \001" +
      "(\0132\035.marmot.proto.SerializedProto\"\206\001\n\023Co" +
      "mbineByGroupProto\022\023\n\013key_columns\030\001 \001(\t\022\023" +
      "\n\013tag_columns\030\002 \001(\t\022\025\n\rorder_columns\030\003 \001" +
      "(\t\022.\n\007reducer\030\004 \001(\0132\035.marmot.proto.Seria" +
      "lizedProto\"r\n\024FinalizeByGroupProto\022\023\n\013ke" +
      "y_columns\030\001 \001(\t\022\023\n\013tag_columns\030\002 \001(\t\0220\n\t" +
      "finalizer\030\003 \001(\0132\035.marmot.proto.Serialize" +
      "dProto\"\200\001\n$AggregateIntermByGroupAtMapSi" +
      "deProto\022\023\n\013key_columns\030\001 \001(\t\022\023\n\013tag_colu" +
      "mns\030\002 \001(\t\022.\n\007reducer\030\003 \001(\0132\035.marmot.prot" +
      "o.SerializedProto\"q\n\032TakeNByGroupAtMapSi" +
      "deProto\022\023\n\013key_columns\030\001 \001(\t\022\023\n\013tag_colu" +
      "mns\030\002 \001(\t\022\025\n\rorder_columns\030\003 \001(\t\022\022\n\ntake" +
      "_count\030\004 \001(\005\"\224\001\n!ReduceIntermByGroupAtMa" +
      "pSideProto\022\023\n\013key_columns\030\001 \001(\t\022\023\n\013tag_c" +
      "olumns\030\002 \001(\t\022\025\n\rorder_columns\030\003 \001(\t\022.\n\007r" +
      "educer\030\004 \001(\0132\035.marmot.proto.SerializedPr" +
      "oto\"\036\n\034IdentityRecordTransformProto\"\"\n\021T" +
      "akeCombinerProto\022\r\n\005count\030\001 \001(\003\"U\n\024MapOu" +
      "tputWriterProto\022\035\n\023map_output_key_cols\030\001" +
      " \001(\tH\000B\036\n\034optional_map_output_key_cols\")" +
      "\n\031IntermediateTerminalProto\022\014\n\004path\030\001 \001(" +
      "\t\"Z\n\024AssignClusterIdProto\022\027\n\017feature_col" +
      "umns\030\001 \001(\t\022\026\n\016cluster_column\030\002 \001(\t\022\021\n\tce" +
      "ntroids\030\003 \001(\014\"\210\001\n\024KMeansIterationProto\022\026" +
      "\n\016workspace_path\030\001 \001(\t\022\027\n\017feature_column" +
      "s\030\002 \001(\t\022\026\n\016cluster_column\030\003 \001(\t\022\021\n\tcentr" +
      "oids\030\004 \001(\014\022\024\n\014worker_count\030\005 \001(\005\"\271\001\n!Cal" +
      "cGlobalMoranIIntermediateProto\022\017\n\007datase" +
      "t\030\001 \001(\t\022\027\n\017geometry_column\030\002 \001(\t\022\025\n\rtarg" +
      "et_column\030\003 \001(\t\022\016\n\006radius\030\004 \001(\001\0222\n\005wtype" +
      "\030\005 \001(\0162#.marmot.proto.optor.LISAWeightPr" +
      "oto\022\017\n\007average\030\006 \001(\001\"A\n\023LISAParametersPr" +
      "oto\022\r\n\005count\030\001 \001(\003\022\013\n\003avg\030\002 \001(\001\022\016\n\006stdde" +
      "v\030\003 \001(\001\"\334\001\n\023CalcGetisOrdGiProto\022\017\n\007datas" +
      "et\030\001 \001(\t\022\027\n\017geometry_column\030\002 \001(\t\022\024\n\014val" +
      "ue_column\030\003 \001(\t\022\016\n\006radius\030\004 \001(\001\0228\n\013weigh" +
      "t_type\030\005 \001(\0162#.marmot.proto.optor.LISAWe" +
      "ightProto\022;\n\nparameters\030\006 \001(\0132\'.marmot.p" +
      "roto.optor.LISAParametersProto\"\361\001\n\025CalcL" +
      "ocalMoransIProto\022\017\n\007dataset\030\001 \001(\t\022\027\n\017geo" +
      "metry_column\030\002 \001(\t\022\024\n\014value_column\030\003 \001(\t" +
      "\022\021\n\tid_column\030\004 \001(\t\022\016\n\006radius\030\005 \001(\001\0228\n\013w" +
      "eight_type\030\006 \001(\0162#.marmot.proto.optor.LI" +
      "SAWeightProto\022;\n\nparameters\030\007 \001(\0132\'.marm" +
      "ot.proto.optor.LISAParametersProto\"\255\001\n\035M" +
      "BRTaggedOpaqueTransformProto\022>\n\017geometry" +
      "_column\030\001 \001(\0132%.marmot.proto.GeometryCol" +
      "umnInfoProto\0223\n\014valid_bounds\030\002 \001(\0132\033.mar" +
      "mot.proto.EnvelopeProtoH\000B\027\n\025optional_va" +
      "lid_bounds\"\212\001\n\023SplitQuadSpaceProto\022C\n\024ge" +
      "ometry_column_info\030\001 \001(\0132%.marmot.proto." +
      "GeometryColumnInfoProto\022\032\n\022max_quadkey_l" +
      "ength\030\002 \001(\005\022\022\n\nsplit_size\030\003 \001(\003\"\215\001\n\035Crea" +
      "teIndexedClusterPackProto\022\023\n\013cluster_dir" +
      "\030\001 \001(\t\022C\n\024geometry_column_info\030\002 \001(\0132%.m" +
      "armot.proto.GeometryColumnInfoProto\022\022\n\nb" +
      "lock_size\030\003 \001(\003\"\207\001\n\034StoreSpatialClusterP" +
      "ackProto\022\r\n\005ds_id\030\001 \001(\t\022\027\n\017partition_cou" +
      "nt\030\002 \001(\005\022?\n\007options\030\003 \001(\0132..marmot.proto" +
      ".service.StoreDataSetOptionsProtoB\026\n\022mar" +
      "mot.proto.optorP\001P\000P\001P\002P\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          marmot.proto.Marmot.getDescriptor(),
          marmot.proto.MarmotInternal.getDescriptor(),
          marmot.proto.optor.MarmotOptor.getDescriptor(),
          marmot.proto.service.MarmotService.getDescriptor(),
        }, assigner);
    internal_static_marmot_proto_optor_BuildThumbnailProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_marmot_proto_optor_BuildThumbnailProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_BuildThumbnailProto_descriptor,
        new java.lang.String[] { "GeomColumn", "SampleRatio", });
    internal_static_marmot_proto_optor_StoreDataSetPartitionProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_marmot_proto_optor_StoreDataSetPartitionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_StoreDataSetPartitionProto_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_marmot_proto_optor_UpdateDataSetInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_marmot_proto_optor_UpdateDataSetInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_UpdateDataSetInfoProto_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_marmot_proto_optor_MapReduceEquiJoinProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_MapReduceEquiJoinProto_descriptor,
        new java.lang.String[] { "JoinColumns", "ParamDataset", "ParamColumns", "OutputColumnExpr", "JoinOptions", });
    internal_static_marmot_proto_optor_TagJoinKeyColumnsProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_marmot_proto_optor_TagJoinKeyColumnsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_TagJoinKeyColumnsProto_descriptor,
        new java.lang.String[] { "JoinColumns", "ParamDataset", "ParamColumns", });
    internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_marmot_proto_optor_JoinPartitionsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_JoinPartitionsProto_descriptor,
        new java.lang.String[] { "JoinColumns", "LeftPrefix", "LeftRecordSchema", "RightPrefix", "RightRecordSchema", "OutputColumnExpr", "JoinType", });
    internal_static_marmot_proto_optor_LeftOuterJoinAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_marmot_proto_optor_LeftOuterJoinAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_LeftOuterJoinAtMapSideProto_descriptor,
        new java.lang.String[] { "InputJoinColumns", "ParamDataset", "ParamJoinColumns", "OutputColumnExpr", });
    internal_static_marmot_proto_optor_SemiJoinAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_marmot_proto_optor_SemiJoinAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_SemiJoinAtMapSideProto_descriptor,
        new java.lang.String[] { "InputJoinColumns", "ParamDataset", "ParamJoinColumns", });
    internal_static_marmot_proto_optor_VARIntermediateProducerProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_marmot_proto_optor_VARIntermediateProducerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_VARIntermediateProducerProto_descriptor,
        new java.lang.String[] { "Aggregators", });
    internal_static_marmot_proto_optor_VARIntermediateCombinerProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_marmot_proto_optor_VARIntermediateCombinerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_VARIntermediateCombinerProto_descriptor,
        new java.lang.String[] { "Aggregators", });
    internal_static_marmot_proto_optor_VARIntermediateFinalizerProto_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_marmot_proto_optor_VARIntermediateFinalizerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_VARIntermediateFinalizerProto_descriptor,
        new java.lang.String[] { "Aggregators", });
    internal_static_marmot_proto_optor_AggregateIntermAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_marmot_proto_optor_AggregateIntermAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_AggregateIntermAtMapSideProto_descriptor,
        new java.lang.String[] { "Reducer", });
    internal_static_marmot_proto_optor_ProduceByGroupProto_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_marmot_proto_optor_ProduceByGroupProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_ProduceByGroupProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "Producer", });
    internal_static_marmot_proto_optor_CombineByGroupProto_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_marmot_proto_optor_CombineByGroupProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_CombineByGroupProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "OrderColumns", "Reducer", });
    internal_static_marmot_proto_optor_FinalizeByGroupProto_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_marmot_proto_optor_FinalizeByGroupProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_FinalizeByGroupProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "Finalizer", });
    internal_static_marmot_proto_optor_AggregateIntermByGroupAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_marmot_proto_optor_AggregateIntermByGroupAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_AggregateIntermByGroupAtMapSideProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "Reducer", });
    internal_static_marmot_proto_optor_TakeNByGroupAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_marmot_proto_optor_TakeNByGroupAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_TakeNByGroupAtMapSideProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "OrderColumns", "TakeCount", });
    internal_static_marmot_proto_optor_ReduceIntermByGroupAtMapSideProto_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_marmot_proto_optor_ReduceIntermByGroupAtMapSideProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_ReduceIntermByGroupAtMapSideProto_descriptor,
        new java.lang.String[] { "KeyColumns", "TagColumns", "OrderColumns", "Reducer", });
    internal_static_marmot_proto_optor_IdentityRecordTransformProto_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_marmot_proto_optor_IdentityRecordTransformProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_IdentityRecordTransformProto_descriptor,
        new java.lang.String[] { });
    internal_static_marmot_proto_optor_TakeCombinerProto_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_marmot_proto_optor_TakeCombinerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_TakeCombinerProto_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_marmot_proto_optor_MapOutputWriterProto_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_marmot_proto_optor_MapOutputWriterProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_MapOutputWriterProto_descriptor,
        new java.lang.String[] { "MapOutputKeyCols", "OptionalMapOutputKeyCols", });
    internal_static_marmot_proto_optor_IntermediateTerminalProto_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_marmot_proto_optor_IntermediateTerminalProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_IntermediateTerminalProto_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_marmot_proto_optor_AssignClusterIdProto_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_marmot_proto_optor_AssignClusterIdProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_AssignClusterIdProto_descriptor,
        new java.lang.String[] { "FeatureColumns", "ClusterColumn", "Centroids", });
    internal_static_marmot_proto_optor_KMeansIterationProto_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_marmot_proto_optor_KMeansIterationProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_KMeansIterationProto_descriptor,
        new java.lang.String[] { "WorkspacePath", "FeatureColumns", "ClusterColumn", "Centroids", "WorkerCount", });
    internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_CalcGlobalMoranIIntermediateProto_descriptor,
        new java.lang.String[] { "Dataset", "GeometryColumn", "TargetColumn", "Radius", "Wtype", "Average", });
    internal_static_marmot_proto_optor_LISAParametersProto_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_marmot_proto_optor_LISAParametersProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_LISAParametersProto_descriptor,
        new java.lang.String[] { "Count", "Avg", "Stddev", });
    internal_static_marmot_proto_optor_CalcGetisOrdGiProto_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_marmot_proto_optor_CalcGetisOrdGiProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_CalcGetisOrdGiProto_descriptor,
        new java.lang.String[] { "Dataset", "GeometryColumn", "ValueColumn", "Radius", "WeightType", "Parameters", });
    internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_marmot_proto_optor_CalcLocalMoransIProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_CalcLocalMoransIProto_descriptor,
        new java.lang.String[] { "Dataset", "GeometryColumn", "ValueColumn", "IdColumn", "Radius", "WeightType", "Parameters", });
    internal_static_marmot_proto_optor_MBRTaggedOpaqueTransformProto_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_marmot_proto_optor_MBRTaggedOpaqueTransformProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_MBRTaggedOpaqueTransformProto_descriptor,
        new java.lang.String[] { "GeometryColumn", "ValidBounds", "OptionalValidBounds", });
    internal_static_marmot_proto_optor_SplitQuadSpaceProto_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_marmot_proto_optor_SplitQuadSpaceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_SplitQuadSpaceProto_descriptor,
        new java.lang.String[] { "GeometryColumnInfo", "MaxQuadkeyLength", "SplitSize", });
    internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_CreateIndexedClusterPackProto_descriptor,
        new java.lang.String[] { "ClusterDir", "GeometryColumnInfo", "BlockSize", });
    internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor,
        new java.lang.String[] { "DsId", "PartitionCount", "Options", });
    marmot.proto.Marmot.getDescriptor();
    marmot.proto.MarmotInternal.getDescriptor();
    marmot.proto.optor.MarmotOptor.getDescriptor();
    marmot.proto.service.MarmotService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
