// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface ProduceByGroupProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.ProduceByGroupProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_columns = 1;</code>
   */
  java.lang.String getKeyColumns();
  /**
   * <code>string key_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyColumnsBytes();

  /**
   * <code>string tag_columns = 2;</code>
   */
  java.lang.String getTagColumns();
  /**
   * <code>string tag_columns = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagColumnsBytes();

  /**
   * <code>.marmot.proto.SerializedProto producer = 3;</code>
   */
  boolean hasProducer();
  /**
   * <code>.marmot.proto.SerializedProto producer = 3;</code>
   */
  marmot.proto.SerializedProto getProducer();
  /**
   * <code>.marmot.proto.SerializedProto producer = 3;</code>
   */
  marmot.proto.SerializedProtoOrBuilder getProducerOrBuilder();
}
