// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface SemiJoinAtMapSideProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.SemiJoinAtMapSideProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input_join_columns = 1;</code>
   */
  java.lang.String getInputJoinColumns();
  /**
   * <code>string input_join_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputJoinColumnsBytes();

  /**
   * <code>string param_dataset = 2;</code>
   */
  java.lang.String getParamDataset();
  /**
   * <code>string param_dataset = 2;</code>
   */
  com.google.protobuf.ByteString
      getParamDatasetBytes();

  /**
   * <code>string param_join_columns = 3;</code>
   */
  java.lang.String getParamJoinColumns();
  /**
   * <code>string param_join_columns = 3;</code>
   */
  com.google.protobuf.ByteString
      getParamJoinColumnsBytes();
}
