// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface SplitQuadSpaceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.SplitQuadSpaceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 1;</code>
   */
  boolean hasGeometryColumnInfo();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 1;</code>
   */
  marmot.proto.GeometryColumnInfoProto getGeometryColumnInfo();
  /**
   * <code>.marmot.proto.GeometryColumnInfoProto geometry_column_info = 1;</code>
   */
  marmot.proto.GeometryColumnInfoProtoOrBuilder getGeometryColumnInfoOrBuilder();

  /**
   * <code>int32 max_quadkey_length = 2;</code>
   */
  int getMaxQuadkeyLength();

  /**
   * <code>int64 split_size = 3;</code>
   */
  long getSplitSize();
}
