// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

/**
 * Protobuf type {@code marmot.proto.optor.StoreSpatialClusterPackProto}
 */
public  final class StoreSpatialClusterPackProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marmot.proto.optor.StoreSpatialClusterPackProto)
    StoreSpatialClusterPackProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StoreSpatialClusterPackProto.newBuilder() to construct.
  private StoreSpatialClusterPackProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StoreSpatialClusterPackProto() {
    dsId_ = "";
    partitionCount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StoreSpatialClusterPackProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dsId_ = s;
            break;
          }
          case 16: {

            partitionCount_ = input.readInt32();
            break;
          }
          case 26: {
            marmot.proto.service.StoreDataSetOptionsProto.Builder subBuilder = null;
            if (options_ != null) {
              subBuilder = options_.toBuilder();
            }
            options_ = input.readMessage(marmot.proto.service.StoreDataSetOptionsProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(options_);
              options_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            marmot.proto.optor.StoreSpatialClusterPackProto.class, marmot.proto.optor.StoreSpatialClusterPackProto.Builder.class);
  }

  public static final int DS_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object dsId_;
  /**
   * <code>string ds_id = 1;</code>
   */
  public java.lang.String getDsId() {
    java.lang.Object ref = dsId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dsId_ = s;
      return s;
    }
  }
  /**
   * <code>string ds_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDsIdBytes() {
    java.lang.Object ref = dsId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dsId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_COUNT_FIELD_NUMBER = 2;
  private int partitionCount_;
  /**
   * <code>int32 partition_count = 2;</code>
   */
  public int getPartitionCount() {
    return partitionCount_;
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private marmot.proto.service.StoreDataSetOptionsProto options_;
  /**
   * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
   */
  public boolean hasOptions() {
    return options_ != null;
  }
  /**
   * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
   */
  public marmot.proto.service.StoreDataSetOptionsProto getOptions() {
    return options_ == null ? marmot.proto.service.StoreDataSetOptionsProto.getDefaultInstance() : options_;
  }
  /**
   * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
   */
  public marmot.proto.service.StoreDataSetOptionsProtoOrBuilder getOptionsOrBuilder() {
    return getOptions();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDsIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dsId_);
    }
    if (partitionCount_ != 0) {
      output.writeInt32(2, partitionCount_);
    }
    if (options_ != null) {
      output.writeMessage(3, getOptions());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDsIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dsId_);
    }
    if (partitionCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, partitionCount_);
    }
    if (options_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOptions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof marmot.proto.optor.StoreSpatialClusterPackProto)) {
      return super.equals(obj);
    }
    marmot.proto.optor.StoreSpatialClusterPackProto other = (marmot.proto.optor.StoreSpatialClusterPackProto) obj;

    boolean result = true;
    result = result && getDsId()
        .equals(other.getDsId());
    result = result && (getPartitionCount()
        == other.getPartitionCount());
    result = result && (hasOptions() == other.hasOptions());
    if (hasOptions()) {
      result = result && getOptions()
          .equals(other.getOptions());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDsId().hashCode();
    hash = (37 * hash) + PARTITION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionCount();
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static marmot.proto.optor.StoreSpatialClusterPackProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(marmot.proto.optor.StoreSpatialClusterPackProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marmot.proto.optor.StoreSpatialClusterPackProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marmot.proto.optor.StoreSpatialClusterPackProto)
      marmot.proto.optor.StoreSpatialClusterPackProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marmot.proto.optor.StoreSpatialClusterPackProto.class, marmot.proto.optor.StoreSpatialClusterPackProto.Builder.class);
    }

    // Construct using marmot.proto.optor.StoreSpatialClusterPackProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dsId_ = "";

      partitionCount_ = 0;

      if (optionsBuilder_ == null) {
        options_ = null;
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return marmot.proto.optor.MarmotOptorInternal.internal_static_marmot_proto_optor_StoreSpatialClusterPackProto_descriptor;
    }

    public marmot.proto.optor.StoreSpatialClusterPackProto getDefaultInstanceForType() {
      return marmot.proto.optor.StoreSpatialClusterPackProto.getDefaultInstance();
    }

    public marmot.proto.optor.StoreSpatialClusterPackProto build() {
      marmot.proto.optor.StoreSpatialClusterPackProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public marmot.proto.optor.StoreSpatialClusterPackProto buildPartial() {
      marmot.proto.optor.StoreSpatialClusterPackProto result = new marmot.proto.optor.StoreSpatialClusterPackProto(this);
      result.dsId_ = dsId_;
      result.partitionCount_ = partitionCount_;
      if (optionsBuilder_ == null) {
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof marmot.proto.optor.StoreSpatialClusterPackProto) {
        return mergeFrom((marmot.proto.optor.StoreSpatialClusterPackProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(marmot.proto.optor.StoreSpatialClusterPackProto other) {
      if (other == marmot.proto.optor.StoreSpatialClusterPackProto.getDefaultInstance()) return this;
      if (!other.getDsId().isEmpty()) {
        dsId_ = other.dsId_;
        onChanged();
      }
      if (other.getPartitionCount() != 0) {
        setPartitionCount(other.getPartitionCount());
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      marmot.proto.optor.StoreSpatialClusterPackProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (marmot.proto.optor.StoreSpatialClusterPackProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dsId_ = "";
    /**
     * <code>string ds_id = 1;</code>
     */
    public java.lang.String getDsId() {
      java.lang.Object ref = dsId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dsId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ds_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDsIdBytes() {
      java.lang.Object ref = dsId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dsId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ds_id = 1;</code>
     */
    public Builder setDsId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dsId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ds_id = 1;</code>
     */
    public Builder clearDsId() {
      
      dsId_ = getDefaultInstance().getDsId();
      onChanged();
      return this;
    }
    /**
     * <code>string ds_id = 1;</code>
     */
    public Builder setDsIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dsId_ = value;
      onChanged();
      return this;
    }

    private int partitionCount_ ;
    /**
     * <code>int32 partition_count = 2;</code>
     */
    public int getPartitionCount() {
      return partitionCount_;
    }
    /**
     * <code>int32 partition_count = 2;</code>
     */
    public Builder setPartitionCount(int value) {
      
      partitionCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 partition_count = 2;</code>
     */
    public Builder clearPartitionCount() {
      
      partitionCount_ = 0;
      onChanged();
      return this;
    }

    private marmot.proto.service.StoreDataSetOptionsProto options_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.service.StoreDataSetOptionsProto, marmot.proto.service.StoreDataSetOptionsProto.Builder, marmot.proto.service.StoreDataSetOptionsProtoOrBuilder> optionsBuilder_;
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public boolean hasOptions() {
      return optionsBuilder_ != null || options_ != null;
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public marmot.proto.service.StoreDataSetOptionsProto getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? marmot.proto.service.StoreDataSetOptionsProto.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public Builder setOptions(marmot.proto.service.StoreDataSetOptionsProto value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
        onChanged();
      } else {
        optionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public Builder setOptions(
        marmot.proto.service.StoreDataSetOptionsProto.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
        onChanged();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public Builder mergeOptions(marmot.proto.service.StoreDataSetOptionsProto value) {
      if (optionsBuilder_ == null) {
        if (options_ != null) {
          options_ =
            marmot.proto.service.StoreDataSetOptionsProto.newBuilder(options_).mergeFrom(value).buildPartial();
        } else {
          options_ = value;
        }
        onChanged();
      } else {
        optionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = null;
        onChanged();
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public marmot.proto.service.StoreDataSetOptionsProto.Builder getOptionsBuilder() {
      
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    public marmot.proto.service.StoreDataSetOptionsProtoOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ?
            marmot.proto.service.StoreDataSetOptionsProto.getDefaultInstance() : options_;
      }
    }
    /**
     * <code>.marmot.proto.service.StoreDataSetOptionsProto options = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        marmot.proto.service.StoreDataSetOptionsProto, marmot.proto.service.StoreDataSetOptionsProto.Builder, marmot.proto.service.StoreDataSetOptionsProtoOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            marmot.proto.service.StoreDataSetOptionsProto, marmot.proto.service.StoreDataSetOptionsProto.Builder, marmot.proto.service.StoreDataSetOptionsProtoOrBuilder>(
                getOptions(),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marmot.proto.optor.StoreSpatialClusterPackProto)
  }

  // @@protoc_insertion_point(class_scope:marmot.proto.optor.StoreSpatialClusterPackProto)
  private static final marmot.proto.optor.StoreSpatialClusterPackProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new marmot.proto.optor.StoreSpatialClusterPackProto();
  }

  public static marmot.proto.optor.StoreSpatialClusterPackProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StoreSpatialClusterPackProto>
      PARSER = new com.google.protobuf.AbstractParser<StoreSpatialClusterPackProto>() {
    public StoreSpatialClusterPackProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StoreSpatialClusterPackProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StoreSpatialClusterPackProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StoreSpatialClusterPackProto> getParserForType() {
    return PARSER;
  }

  public marmot.proto.optor.StoreSpatialClusterPackProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

