// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marmot.optor.internal.proto

package marmot.proto.optor;

public interface TakeNByGroupAtMapSideProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marmot.proto.optor.TakeNByGroupAtMapSideProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_columns = 1;</code>
   */
  java.lang.String getKeyColumns();
  /**
   * <code>string key_columns = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyColumnsBytes();

  /**
   * <code>string tag_columns = 2;</code>
   */
  java.lang.String getTagColumns();
  /**
   * <code>string tag_columns = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagColumnsBytes();

  /**
   * <code>string order_columns = 3;</code>
   */
  java.lang.String getOrderColumns();
  /**
   * <code>string order_columns = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrderColumnsBytes();

  /**
   * <code>int32 take_count = 4;</code>
   */
  int getTakeCount();
}
